---
extends: default

rules:
  # Relax line length for readability
  line-length:
    max: 120
    level: warning

  # Don't require document start markers
  document-start: disable

  # Allow on: true/false in GitHub Actions
  truthy:
    allowed-values: ['true', 'false', 'on', 'off', 'yes', 'no']

  # Relax comment indentation
  comments-indentation: disable

  # Allow inline comments
  comments:
    min-spaces-from-content: 1
