// Code generated by ogen, DO NOT EDIT.

package oas

import (
	"context"
)

// Handler handles operations described by OpenAPI v3 specification.
type Handler interface {
	// ListCalendarEvents implements listCalendarEvents operation.
	//
	// Returns a flat, sorted list of calendar event instances whose time overlaps the requested
	// `[start, end)` window. Single events are returned directly; recurring series are expanded
	// timezone-aware (EXDATEs and cancelled occurrences subtracted, modified occurrences applied). The
	// window is bounded — a request that would expand an excessive range is rejected with a 400 Problem
	// (ADR-0042).
	//
	// GET /calendar/events
	ListCalendarEvents(ctx context.Context, params ListCalendarEventsParams) (ListCalendarEventsRes, error)
	// ListChildcareProviderSuggestions implements listChildcareProviderSuggestions operation.
	//
	// Returns non-archived providers ranked by per-occurrence recent usage: each provider's associated
	// event series' past occurrences are expanded over a recency window, counted per occurrence, and
	// recency-weighted (a weekly slot counts as many; a one-off counts as one). Nothing is stored — the
	// ranking is computed from associations plus expansion, so it can't drift.
	//
	// GET /childcare/providers/suggestions
	ListChildcareProviderSuggestions(ctx context.Context) (ListChildcareProviderSuggestionsRes, error)
	// ListChildcareProviders implements listChildcareProviders operation.
	//
	// Returns the active (non-archived) childcare provider roster. Archived providers are excluded but
	// retained server-side so frequency history is preserved. Local overlay; never written to Google.
	//
	// GET /childcare/providers
	ListChildcareProviders(ctx context.Context) (ListChildcareProvidersRes, error)
	// ListDirectoryPeople implements listDirectoryPeople operation.
	//
	// Returns the active people and groups in the household directory — the roster that feeds the "FOR"
	// subject picker and childcare-provider linking. Local overlay; never reflects Google data.
	//
	// GET /directory/people
	ListDirectoryPeople(ctx context.Context) (ListDirectoryPeopleRes, error)
	// Ping implements ping operation.
	//
	// Returns a small payload confirming the API is reachable and the caller's bearer token was accepted.
	// This is the placeholder endpoint that establishes the read platform; domain endpoints (calendar,
	// directory, childcare) are added against it in later slices. Distinct from the unauthenticated
	// `/health` probe, which lives outside the versioned, generated surface for Traefik and Uptime Kuma.
	//
	// GET /ping
	Ping(ctx context.Context) (PingRes, error)
	// NewError creates *ProblemStatusCode from error returned by handler.
	//
	// Used for common default response.
	NewError(ctx context.Context, err error) *ProblemStatusCode
}

// Server implements http server based on OpenAPI v3 specification and
// calls Handler to handle requests.
type Server struct {
	h   Handler
	sec SecurityHandler
	baseServer
}

// NewServer creates new Server.
func NewServer(h Handler, sec SecurityHandler, opts ...ServerOption) (*Server, error) {
	s, err := newServerConfig(opts...).baseServer()
	if err != nil {
		return nil, err
	}
	return &Server{
		h:          h,
		sec:        sec,
		baseServer: s,
	}, nil
}
