// Code generated by ogen, DO NOT EDIT.
package oas

type ListCalendarEventsRes interface {
	listCalendarEventsRes()
}

type ListChildcareProviderSuggestionsRes interface {
	listChildcareProviderSuggestionsRes()
}

type ListChildcareProvidersRes interface {
	listChildcareProvidersRes()
}

type ListDirectoryPeopleRes interface {
	listDirectoryPeopleRes()
}

type PingRes interface {
	pingRes()
}
