// Code generated by ogen, DO NOT EDIT.

package oas

import (
	"context"

	ht "github.com/ogen-go/ogen/http"
)

// UnimplementedHandler is no-op Handler which returns http.ErrNotImplemented.
type UnimplementedHandler struct{}

var _ Handler = UnimplementedHandler{}

// Ping implements ping operation.
//
// Returns a small payload confirming the API is reachable and the caller's bearer token was accepted.
// This is the placeholder endpoint that establishes the read platform; domain endpoints (calendar,
// directory, childcare) are added against it in later slices. Distinct from the unauthenticated
// `/health` probe, which lives outside the versioned, generated surface for Traefik and Uptime Kuma.
//
// GET /ping
func (UnimplementedHandler) Ping(ctx context.Context) (r PingRes, _ error) {
	return r, ht.ErrNotImplemented
}

// NewError creates *ProblemStatusCode from error returned by handler.
//
// Used for common default response.
func (UnimplementedHandler) NewError(ctx context.Context, err error) (r *ProblemStatusCode) {
	r = new(ProblemStatusCode)
	return r
}
