// Code generated by ogen, DO NOT EDIT.

package oas

import (
	"context"

	ht "github.com/ogen-go/ogen/http"
)

// UnimplementedHandler is no-op Handler which returns http.ErrNotImplemented.
type UnimplementedHandler struct{}

var _ Handler = UnimplementedHandler{}

// ListCalendarEvents implements listCalendarEvents operation.
//
// Returns a flat, sorted list of calendar event instances whose time overlaps the requested
// `[start, end)` window. Single events are returned directly; recurring series are expanded
// timezone-aware (EXDATEs and cancelled occurrences subtracted, modified occurrences applied). The
// window is bounded — a request that would expand an excessive range is rejected with a 400 Problem
// (ADR-0042).
//
// GET /calendar/events
func (UnimplementedHandler) ListCalendarEvents(ctx context.Context, params ListCalendarEventsParams) (r ListCalendarEventsRes, _ error) {
	return r, ht.ErrNotImplemented
}

// ListChildcareProviderSuggestions implements listChildcareProviderSuggestions operation.
//
// Returns non-archived providers ranked by per-occurrence recent usage: each provider's associated
// event series' past occurrences are expanded over a recency window, counted per occurrence, and
// recency-weighted (a weekly slot counts as many; a one-off counts as one). Nothing is stored — the
// ranking is computed from associations plus expansion, so it can't drift.
//
// GET /childcare/providers/suggestions
func (UnimplementedHandler) ListChildcareProviderSuggestions(ctx context.Context) (r ListChildcareProviderSuggestionsRes, _ error) {
	return r, ht.ErrNotImplemented
}

// ListChildcareProviders implements listChildcareProviders operation.
//
// Returns the active (non-archived) childcare provider roster. Archived providers are excluded but
// retained server-side so frequency history is preserved. Local overlay; never written to Google.
//
// GET /childcare/providers
func (UnimplementedHandler) ListChildcareProviders(ctx context.Context) (r ListChildcareProvidersRes, _ error) {
	return r, ht.ErrNotImplemented
}

// ListDirectoryPeople implements listDirectoryPeople operation.
//
// Returns the active people and groups in the household directory — the roster that feeds the "FOR"
// subject picker and childcare-provider linking. Local overlay; never reflects Google data.
//
// GET /directory/people
func (UnimplementedHandler) ListDirectoryPeople(ctx context.Context) (r ListDirectoryPeopleRes, _ error) {
	return r, ht.ErrNotImplemented
}

// Ping implements ping operation.
//
// Returns a small payload confirming the API is reachable and the caller's bearer token was accepted.
// This is the placeholder endpoint that establishes the read platform; domain endpoints (calendar,
// directory, childcare) are added against it in later slices. Distinct from the unauthenticated
// `/health` probe, which lives outside the versioned, generated surface for Traefik and Uptime Kuma.
//
// GET /ping
func (UnimplementedHandler) Ping(ctx context.Context) (r PingRes, _ error) {
	return r, ht.ErrNotImplemented
}

// NewError creates *ProblemStatusCode from error returned by handler.
//
// Used for common default response.
func (UnimplementedHandler) NewError(ctx context.Context, err error) (r *ProblemStatusCode) {
	r = new(ProblemStatusCode)
	return r
}
