// Code generated by ogen, DO NOT EDIT.

package oas

import (
	"net/http"
	"time"

	"github.com/ogen-go/ogen/conv"
	"github.com/ogen-go/ogen/middleware"
	"github.com/ogen-go/ogen/ogenerrors"
	"github.com/ogen-go/ogen/uri"
)

// ListCalendarEventsParams is parameters of listCalendarEvents operation.
type ListCalendarEventsParams struct {
	// Inclusive start of the window, as an RFC 3339 timestamp.
	Start time.Time
	// Exclusive end of the window, as an RFC 3339 timestamp. Must be after start and within the maximum
	// window.
	End time.Time
}

func unpackListCalendarEventsParams(packed middleware.Parameters) (params ListCalendarEventsParams) {
	{
		key := middleware.ParameterKey{
			Name: "start",
			In:   "query",
		}
		params.Start = packed[key].(time.Time)
	}
	{
		key := middleware.ParameterKey{
			Name: "end",
			In:   "query",
		}
		params.End = packed[key].(time.Time)
	}
	return params
}

func decodeListCalendarEventsParams(args [0]string, argsEscaped bool, r *http.Request) (params ListCalendarEventsParams, _ error) {
	q := uri.NewQueryDecoder(r.URL.Query())
	// Decode query: start.
	if err := func() error {
		cfg := uri.QueryParameterDecodingConfig{
			Name:    "start",
			Style:   uri.QueryStyleForm,
			Explode: true,
		}

		if err := q.HasParam(cfg); err == nil {
			if err := q.DecodeParam(cfg, func(d uri.Decoder) error {
				val, err := d.DecodeValue()
				if err != nil {
					return err
				}

				c, err := conv.ToDateTime(val)
				if err != nil {
					return err
				}

				params.Start = c
				return nil
			}); err != nil {
				return err
			}
		} else {
			return err
		}
		return nil
	}(); err != nil {
		return params, &ogenerrors.DecodeParamError{
			Name: "start",
			In:   "query",
			Err:  err,
		}
	}
	// Decode query: end.
	if err := func() error {
		cfg := uri.QueryParameterDecodingConfig{
			Name:    "end",
			Style:   uri.QueryStyleForm,
			Explode: true,
		}

		if err := q.HasParam(cfg); err == nil {
			if err := q.DecodeParam(cfg, func(d uri.Decoder) error {
				val, err := d.DecodeValue()
				if err != nil {
					return err
				}

				c, err := conv.ToDateTime(val)
				if err != nil {
					return err
				}

				params.End = c
				return nil
			}); err != nil {
				return err
			}
		} else {
			return err
		}
		return nil
	}(); err != nil {
		return params, &ogenerrors.DecodeParamError{
			Name: "end",
			In:   "query",
			Err:  err,
		}
	}
	return params, nil
}
