// Code generated by ogen, DO NOT EDIT.

package oas

// OperationName is the ogen operation name
type OperationName = string

const (
	ListCalendarEventsOperation OperationName = "ListCalendarEvents"
	PingOperation               OperationName = "Ping"
)
