// Code generated by ogen, DO NOT EDIT.

package oas

import (
	"fmt"
	"time"
)

func (s *ProblemStatusCode) Error() string {
	return fmt.Sprintf("code %d: %+v", s.StatusCode, s.Response)
}

type BearerAuth struct {
	Token string
	Roles []string
}

// GetToken returns the value of Token.
func (s *BearerAuth) GetToken() string {
	return s.Token
}

// GetRoles returns the value of Roles.
func (s *BearerAuth) GetRoles() []string {
	return s.Roles
}

// SetToken sets the value of Token.
func (s *BearerAuth) SetToken(val string) {
	s.Token = val
}

// SetRoles sets the value of Roles.
func (s *BearerAuth) SetRoles(val []string) {
	s.Roles = val
}

// One concrete occurrence of a calendar event in the requested window. Recurring series are expanded
// into instances server-side, timezone-aware. Times are RFC 3339 UTC instants; for all-day events
// `all_day` is true and `end` is EXCLUSIVE (a one-day event on the 26th ends on the 27th — surfaced,
// not hidden; see ADR-0042). `subjects` and `childcare` are resolved from the local overlay (populated
// in the household-overlay slice).
// Ref: #/components/schemas/CalendarInstance
type CalendarInstance struct {
	// The Google event id of the master (or override child) this instance came from.
	GoogleEventID string `json:"google_event_id"`
	// The event title.
	Summary OptString `json:"summary"`
	// Instance start as an RFC 3339 UTC instant.
	Start time.Time `json:"start"`
	// Instance end as an RFC 3339 UTC instant (exclusive for all-day events).
	End time.Time `json:"end"`
	// Whether this is an all-day event (date-only in Google).
	AllDay bool `json:"all_day"`
	// Google event status — confirmed, tentative, or cancelled.
	Status string `json:"status"`
	// Free-text location, when set.
	Location OptString `json:"location"`
	// Free-text description, when set.
	Description OptString `json:"description"`
	// Resolved subject person ids (the "FOR" lane) — local overlay, never written to Google.
	Subjects []string `json:"subjects"`
	// Resolved childcare provider id for this event; omitted when none — local overlay.
	Childcare OptString `json:"childcare"`
	// Google attendees, each reconciled to a directory person id by email where matched, with Google RSVP
	// status.
	Attendees []CalendarInstanceAttendeesItem `json:"attendees"`
}

// GetGoogleEventID returns the value of GoogleEventID.
func (s *CalendarInstance) GetGoogleEventID() string {
	return s.GoogleEventID
}

// GetSummary returns the value of Summary.
func (s *CalendarInstance) GetSummary() OptString {
	return s.Summary
}

// GetStart returns the value of Start.
func (s *CalendarInstance) GetStart() time.Time {
	return s.Start
}

// GetEnd returns the value of End.
func (s *CalendarInstance) GetEnd() time.Time {
	return s.End
}

// GetAllDay returns the value of AllDay.
func (s *CalendarInstance) GetAllDay() bool {
	return s.AllDay
}

// GetStatus returns the value of Status.
func (s *CalendarInstance) GetStatus() string {
	return s.Status
}

// GetLocation returns the value of Location.
func (s *CalendarInstance) GetLocation() OptString {
	return s.Location
}

// GetDescription returns the value of Description.
func (s *CalendarInstance) GetDescription() OptString {
	return s.Description
}

// GetSubjects returns the value of Subjects.
func (s *CalendarInstance) GetSubjects() []string {
	return s.Subjects
}

// GetChildcare returns the value of Childcare.
func (s *CalendarInstance) GetChildcare() OptString {
	return s.Childcare
}

// GetAttendees returns the value of Attendees.
func (s *CalendarInstance) GetAttendees() []CalendarInstanceAttendeesItem {
	return s.Attendees
}

// SetGoogleEventID sets the value of GoogleEventID.
func (s *CalendarInstance) SetGoogleEventID(val string) {
	s.GoogleEventID = val
}

// SetSummary sets the value of Summary.
func (s *CalendarInstance) SetSummary(val OptString) {
	s.Summary = val
}

// SetStart sets the value of Start.
func (s *CalendarInstance) SetStart(val time.Time) {
	s.Start = val
}

// SetEnd sets the value of End.
func (s *CalendarInstance) SetEnd(val time.Time) {
	s.End = val
}

// SetAllDay sets the value of AllDay.
func (s *CalendarInstance) SetAllDay(val bool) {
	s.AllDay = val
}

// SetStatus sets the value of Status.
func (s *CalendarInstance) SetStatus(val string) {
	s.Status = val
}

// SetLocation sets the value of Location.
func (s *CalendarInstance) SetLocation(val OptString) {
	s.Location = val
}

// SetDescription sets the value of Description.
func (s *CalendarInstance) SetDescription(val OptString) {
	s.Description = val
}

// SetSubjects sets the value of Subjects.
func (s *CalendarInstance) SetSubjects(val []string) {
	s.Subjects = val
}

// SetChildcare sets the value of Childcare.
func (s *CalendarInstance) SetChildcare(val OptString) {
	s.Childcare = val
}

// SetAttendees sets the value of Attendees.
func (s *CalendarInstance) SetAttendees(val []CalendarInstanceAttendeesItem) {
	s.Attendees = val
}

type CalendarInstanceAttendeesItem struct {
	// The attendee's email address (from Google).
	Email string `json:"email"`
	// The matched directory person id, when the email reconciles to a known person.
	PersonID OptString `json:"person_id"`
	// Google RSVP status — needsAction, declined, tentative, or accepted.
	ResponseStatus OptString `json:"response_status"`
}

// GetEmail returns the value of Email.
func (s *CalendarInstanceAttendeesItem) GetEmail() string {
	return s.Email
}

// GetPersonID returns the value of PersonID.
func (s *CalendarInstanceAttendeesItem) GetPersonID() OptString {
	return s.PersonID
}

// GetResponseStatus returns the value of ResponseStatus.
func (s *CalendarInstanceAttendeesItem) GetResponseStatus() OptString {
	return s.ResponseStatus
}

// SetEmail sets the value of Email.
func (s *CalendarInstanceAttendeesItem) SetEmail(val string) {
	s.Email = val
}

// SetPersonID sets the value of PersonID.
func (s *CalendarInstanceAttendeesItem) SetPersonID(val OptString) {
	s.PersonID = val
}

// SetResponseStatus sets the value of ResponseStatus.
func (s *CalendarInstanceAttendeesItem) SetResponseStatus(val OptString) {
	s.ResponseStatus = val
}

type ListCalendarEventsBadRequest Problem

func (*ListCalendarEventsBadRequest) listCalendarEventsRes() {}

type ListCalendarEventsOKApplicationJSON []CalendarInstance

func (*ListCalendarEventsOKApplicationJSON) listCalendarEventsRes() {}

type ListCalendarEventsUnauthorized Problem

func (*ListCalendarEventsUnauthorized) listCalendarEventsRes() {}

type ListChildcareProviderSuggestionsOKApplicationJSON []ProviderSuggestion

func (*ListChildcareProviderSuggestionsOKApplicationJSON) listChildcareProviderSuggestionsRes() {}

type ListChildcareProvidersOKApplicationJSON []Provider

func (*ListChildcareProvidersOKApplicationJSON) listChildcareProvidersRes() {}

type ListDirectoryPeopleOKApplicationJSON []Person

func (*ListDirectoryPeopleOKApplicationJSON) listDirectoryPeopleRes() {}

// NewOptString returns new OptString with value set to v.
func NewOptString(v string) OptString {
	return OptString{
		Value: v,
		Set:   true,
	}
}

// OptString is optional string.
type OptString struct {
	Value string
	Set   bool
}

// IsSet returns true if OptString was set.
func (o OptString) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptString) Reset() {
	var v string
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptString) SetTo(v string) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptString) Get() (v string, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptString) Or(d string) string {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// A person or group in the household directory — feeds the "FOR" subject picker and provider
// linking. Local overlay, never written to Google.
// Ref: #/components/schemas/Person
type Person struct {
	// The person's stable id (UUID).
	ID string `json:"id"`
	// Human-readable name.
	DisplayName string `json:"display_name"`
	// Either `person` or `group` (a group like "Household" has no membership in MVP).
	Kind string `json:"kind"`
	// The Home Assistant person entity id this maps to, when present.
	HaPersonEntityID OptString `json:"ha_person_entity_id"`
	// Email used to reconcile calendar attendees to this person, when present.
	Email OptString `json:"email"`
	// Family grouping used to colour-by-family in clients.
	Family OptString `json:"family"`
	// Display colour, when set.
	Color OptString `json:"color"`
	// Whether the person is active.
	Active bool `json:"active"`
}

// GetID returns the value of ID.
func (s *Person) GetID() string {
	return s.ID
}

// GetDisplayName returns the value of DisplayName.
func (s *Person) GetDisplayName() string {
	return s.DisplayName
}

// GetKind returns the value of Kind.
func (s *Person) GetKind() string {
	return s.Kind
}

// GetHaPersonEntityID returns the value of HaPersonEntityID.
func (s *Person) GetHaPersonEntityID() OptString {
	return s.HaPersonEntityID
}

// GetEmail returns the value of Email.
func (s *Person) GetEmail() OptString {
	return s.Email
}

// GetFamily returns the value of Family.
func (s *Person) GetFamily() OptString {
	return s.Family
}

// GetColor returns the value of Color.
func (s *Person) GetColor() OptString {
	return s.Color
}

// GetActive returns the value of Active.
func (s *Person) GetActive() bool {
	return s.Active
}

// SetID sets the value of ID.
func (s *Person) SetID(val string) {
	s.ID = val
}

// SetDisplayName sets the value of DisplayName.
func (s *Person) SetDisplayName(val string) {
	s.DisplayName = val
}

// SetKind sets the value of Kind.
func (s *Person) SetKind(val string) {
	s.Kind = val
}

// SetHaPersonEntityID sets the value of HaPersonEntityID.
func (s *Person) SetHaPersonEntityID(val OptString) {
	s.HaPersonEntityID = val
}

// SetEmail sets the value of Email.
func (s *Person) SetEmail(val OptString) {
	s.Email = val
}

// SetFamily sets the value of Family.
func (s *Person) SetFamily(val OptString) {
	s.Family = val
}

// SetColor sets the value of Color.
func (s *Person) SetColor(val OptString) {
	s.Color = val
}

// SetActive sets the value of Active.
func (s *Person) SetActive(val bool) {
	s.Active = val
}

type PingOK struct {
	// Always `ok` when the surface is healthy.
	Status string `json:"status"`
	// The service name reporting liveness.
	Service string `json:"service"`
}

// GetStatus returns the value of Status.
func (s *PingOK) GetStatus() string {
	return s.Status
}

// GetService returns the value of Service.
func (s *PingOK) GetService() string {
	return s.Service
}

// SetStatus sets the value of Status.
func (s *PingOK) SetStatus(val string) {
	s.Status = val
}

// SetService sets the value of Service.
func (s *PingOK) SetService(val string) {
	s.Service = val
}

func (*PingOK) pingRes() {}

// RFC 9457 Problem Details. The single error shape returned by every operation in this API (ADR-0041).
// Domain-specific context is carried in extension members rather than by string-munging `detail`.
// Ref: #/components/schemas/Problem
type Problem struct {
	// A URI reference identifying the problem type. Defaults to `about:blank` when no specific type
	// applies.
	Type OptString `json:"type"`
	// A short, human-readable, stable summary of the problem type.
	Title string `json:"title"`
	// The HTTP status code, duplicated here for clients that read the body.
	Status int32 `json:"status"`
	// A human-readable explanation specific to this occurrence of the problem.
	Detail OptString `json:"detail"`
	// A URI reference identifying the specific occurrence (typically the request path).
	Instance OptString `json:"instance"`
}

// GetType returns the value of Type.
func (s *Problem) GetType() OptString {
	return s.Type
}

// GetTitle returns the value of Title.
func (s *Problem) GetTitle() string {
	return s.Title
}

// GetStatus returns the value of Status.
func (s *Problem) GetStatus() int32 {
	return s.Status
}

// GetDetail returns the value of Detail.
func (s *Problem) GetDetail() OptString {
	return s.Detail
}

// GetInstance returns the value of Instance.
func (s *Problem) GetInstance() OptString {
	return s.Instance
}

// SetType sets the value of Type.
func (s *Problem) SetType(val OptString) {
	s.Type = val
}

// SetTitle sets the value of Title.
func (s *Problem) SetTitle(val string) {
	s.Title = val
}

// SetStatus sets the value of Status.
func (s *Problem) SetStatus(val int32) {
	s.Status = val
}

// SetDetail sets the value of Detail.
func (s *Problem) SetDetail(val OptString) {
	s.Detail = val
}

// SetInstance sets the value of Instance.
func (s *Problem) SetInstance(val OptString) {
	s.Instance = val
}

func (*Problem) listChildcareProviderSuggestionsRes() {}
func (*Problem) listChildcareProvidersRes()           {}
func (*Problem) listDirectoryPeopleRes()              {}
func (*Problem) pingRes()                             {}

// ProblemStatusCode wraps Problem with StatusCode.
type ProblemStatusCode struct {
	StatusCode int
	Response   Problem
}

// GetStatusCode returns the value of StatusCode.
func (s *ProblemStatusCode) GetStatusCode() int {
	return s.StatusCode
}

// GetResponse returns the value of Response.
func (s *ProblemStatusCode) GetResponse() Problem {
	return s.Response
}

// SetStatusCode sets the value of StatusCode.
func (s *ProblemStatusCode) SetStatusCode(val int) {
	s.StatusCode = val
}

// SetResponse sets the value of Response.
func (s *ProblemStatusCode) SetResponse(val Problem) {
	s.Response = val
}

// A childcare provider — may be a household person (e.g. a grandparent) or standalone (e.g. a
// daycare). Local overlay.
// Ref: #/components/schemas/Provider
type Provider struct {
	// The provider's stable id (UUID).
	ID string `json:"id"`
	// Human-readable name.
	DisplayName string `json:"display_name"`
	// The linked directory person id, when the provider is also a household person.
	PersonID OptString `json:"person_id"`
	// Free-text relationship to the household, when set.
	Relationship OptString `json:"relationship"`
	// Whether the provider has been archived (soft-deleted; frequency history is preserved).
	Archived bool `json:"archived"`
}

// GetID returns the value of ID.
func (s *Provider) GetID() string {
	return s.ID
}

// GetDisplayName returns the value of DisplayName.
func (s *Provider) GetDisplayName() string {
	return s.DisplayName
}

// GetPersonID returns the value of PersonID.
func (s *Provider) GetPersonID() OptString {
	return s.PersonID
}

// GetRelationship returns the value of Relationship.
func (s *Provider) GetRelationship() OptString {
	return s.Relationship
}

// GetArchived returns the value of Archived.
func (s *Provider) GetArchived() bool {
	return s.Archived
}

// SetID sets the value of ID.
func (s *Provider) SetID(val string) {
	s.ID = val
}

// SetDisplayName sets the value of DisplayName.
func (s *Provider) SetDisplayName(val string) {
	s.DisplayName = val
}

// SetPersonID sets the value of PersonID.
func (s *Provider) SetPersonID(val OptString) {
	s.PersonID = val
}

// SetRelationship sets the value of Relationship.
func (s *Provider) SetRelationship(val OptString) {
	s.Relationship = val
}

// SetArchived sets the value of Archived.
func (s *Provider) SetArchived(val bool) {
	s.Archived = val
}

// A non-archived provider ranked by recent per-occurrence usage (higher score = more
// recently/frequently used).
// Ref: #/components/schemas/ProviderSuggestion
type ProviderSuggestion struct {
	// The provider's id (UUID).
	ID string `json:"id"`
	// Human-readable name.
	DisplayName string `json:"display_name"`
	// Recency-weighted per-occurrence usage score over the recency window.
	Score float64 `json:"score"`
}

// GetID returns the value of ID.
func (s *ProviderSuggestion) GetID() string {
	return s.ID
}

// GetDisplayName returns the value of DisplayName.
func (s *ProviderSuggestion) GetDisplayName() string {
	return s.DisplayName
}

// GetScore returns the value of Score.
func (s *ProviderSuggestion) GetScore() float64 {
	return s.Score
}

// SetID sets the value of ID.
func (s *ProviderSuggestion) SetID(val string) {
	s.ID = val
}

// SetDisplayName sets the value of DisplayName.
func (s *ProviderSuggestion) SetDisplayName(val string) {
	s.DisplayName = val
}

// SetScore sets the value of Score.
func (s *ProviderSuggestion) SetScore(val float64) {
	s.Score = val
}
