// Code generated by ogen, DO NOT EDIT.

package oas

import (
	"context"

	ht "github.com/ogen-go/ogen/http"
)

// UnimplementedHandler is no-op Handler which returns http.ErrNotImplemented.
type UnimplementedHandler struct{}

var _ Handler = UnimplementedHandler{}

// ListCalendarEvents implements listCalendarEvents operation.
//
// Returns a flat, sorted list of calendar event instances whose time overlaps the requested
// `[start, end)` window. Single events are returned directly; recurring series are expanded
// timezone-aware (EXDATEs and cancelled occurrences subtracted, modified occurrences applied). The
// window is bounded — a request that would expand an excessive range is rejected with a 400 Problem
// (ADR-0042).
//
// GET /calendar/events
func (UnimplementedHandler) ListCalendarEvents(ctx context.Context, params ListCalendarEventsParams) (r ListCalendarEventsRes, _ error) {
	return r, ht.ErrNotImplemented
}

// Ping implements ping operation.
//
// Returns a small payload confirming the API is reachable and the caller's bearer token was accepted.
// This is the placeholder endpoint that establishes the read platform; domain endpoints (calendar,
// directory, childcare) are added against it in later slices. Distinct from the unauthenticated
// `/health` probe, which lives outside the versioned, generated surface for Traefik and Uptime Kuma.
//
// GET /ping
func (UnimplementedHandler) Ping(ctx context.Context) (r PingRes, _ error) {
	return r, ht.ErrNotImplemented
}

// NewError creates *ProblemStatusCode from error returned by handler.
//
// Used for common default response.
func (UnimplementedHandler) NewError(ctx context.Context, err error) (r *ProblemStatusCode) {
	r = new(ProblemStatusCode)
	return r
}
