// Code generated by ogen, DO NOT EDIT.

package oas

// OperationName is the ogen operation name
type OperationName = string

const (
	ListCalendarEventsOperation               OperationName = "ListCalendarEvents"
	ListChildcareProviderSuggestionsOperation OperationName = "ListChildcareProviderSuggestions"
	ListChildcareProvidersOperation           OperationName = "ListChildcareProviders"
	ListDirectoryPeopleOperation              OperationName = "ListDirectoryPeople"
	PingOperation                             OperationName = "Ping"
)
