// Code generated by ogen, DO NOT EDIT.

package oas

import (
	"fmt"
)

func (s *ProblemStatusCode) Error() string {
	return fmt.Sprintf("code %d: %+v", s.StatusCode, s.Response)
}

type BearerAuth struct {
	Token string
	Roles []string
}

// GetToken returns the value of Token.
func (s *BearerAuth) GetToken() string {
	return s.Token
}

// GetRoles returns the value of Roles.
func (s *BearerAuth) GetRoles() []string {
	return s.Roles
}

// SetToken sets the value of Token.
func (s *BearerAuth) SetToken(val string) {
	s.Token = val
}

// SetRoles sets the value of Roles.
func (s *BearerAuth) SetRoles(val []string) {
	s.Roles = val
}

// NewOptString returns new OptString with value set to v.
func NewOptString(v string) OptString {
	return OptString{
		Value: v,
		Set:   true,
	}
}

// OptString is optional string.
type OptString struct {
	Value string
	Set   bool
}

// IsSet returns true if OptString was set.
func (o OptString) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptString) Reset() {
	var v string
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptString) SetTo(v string) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptString) Get() (v string, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptString) Or(d string) string {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

type PingOK struct {
	// Always `ok` when the surface is healthy.
	Status string `json:"status"`
	// The service name reporting liveness.
	Service string `json:"service"`
}

// GetStatus returns the value of Status.
func (s *PingOK) GetStatus() string {
	return s.Status
}

// GetService returns the value of Service.
func (s *PingOK) GetService() string {
	return s.Service
}

// SetStatus sets the value of Status.
func (s *PingOK) SetStatus(val string) {
	s.Status = val
}

// SetService sets the value of Service.
func (s *PingOK) SetService(val string) {
	s.Service = val
}

func (*PingOK) pingRes() {}

// RFC 9457 Problem Details. The single error shape returned by every operation in this API (ADR-0041).
// Domain-specific context is carried in extension members rather than by string-munging `detail`.
// Ref: #/components/schemas/Problem
type Problem struct {
	// A URI reference identifying the problem type. Defaults to `about:blank` when no specific type
	// applies.
	Type OptString `json:"type"`
	// A short, human-readable, stable summary of the problem type.
	Title string `json:"title"`
	// The HTTP status code, duplicated here for clients that read the body.
	Status int32 `json:"status"`
	// A human-readable explanation specific to this occurrence of the problem.
	Detail OptString `json:"detail"`
	// A URI reference identifying the specific occurrence (typically the request path).
	Instance OptString `json:"instance"`
}

// GetType returns the value of Type.
func (s *Problem) GetType() OptString {
	return s.Type
}

// GetTitle returns the value of Title.
func (s *Problem) GetTitle() string {
	return s.Title
}

// GetStatus returns the value of Status.
func (s *Problem) GetStatus() int32 {
	return s.Status
}

// GetDetail returns the value of Detail.
func (s *Problem) GetDetail() OptString {
	return s.Detail
}

// GetInstance returns the value of Instance.
func (s *Problem) GetInstance() OptString {
	return s.Instance
}

// SetType sets the value of Type.
func (s *Problem) SetType(val OptString) {
	s.Type = val
}

// SetTitle sets the value of Title.
func (s *Problem) SetTitle(val string) {
	s.Title = val
}

// SetStatus sets the value of Status.
func (s *Problem) SetStatus(val int32) {
	s.Status = val
}

// SetDetail sets the value of Detail.
func (s *Problem) SetDetail(val OptString) {
	s.Detail = val
}

// SetInstance sets the value of Instance.
func (s *Problem) SetInstance(val OptString) {
	s.Instance = val
}

func (*Problem) pingRes() {}

// ProblemStatusCode wraps Problem with StatusCode.
type ProblemStatusCode struct {
	StatusCode int
	Response   Problem
}

// GetStatusCode returns the value of StatusCode.
func (s *ProblemStatusCode) GetStatusCode() int {
	return s.StatusCode
}

// GetResponse returns the value of Response.
func (s *ProblemStatusCode) GetResponse() Problem {
	return s.Response
}

// SetStatusCode sets the value of StatusCode.
func (s *ProblemStatusCode) SetStatusCode(val int) {
	s.StatusCode = val
}

// SetResponse sets the value of Response.
func (s *ProblemStatusCode) SetResponse(val Problem) {
	s.Response = val
}
