// Code generated by ogen, DO NOT EDIT.

package oas

import (
	"context"
)

// Handler handles operations described by OpenAPI v3 specification.
type Handler interface {
	// Ping implements ping operation.
	//
	// Returns a small payload confirming the API is reachable and the caller's bearer token was accepted.
	// This is the placeholder endpoint that establishes the read platform; domain endpoints (calendar,
	// directory, childcare) are added against it in later slices. Distinct from the unauthenticated
	// `/health` probe, which lives outside the versioned, generated surface for Traefik and Uptime Kuma.
	//
	// GET /ping
	Ping(ctx context.Context) (PingRes, error)
	// NewError creates *ProblemStatusCode from error returned by handler.
	//
	// Used for common default response.
	NewError(ctx context.Context, err error) *ProblemStatusCode
}

// Server implements http server based on OpenAPI v3 specification and
// calls Handler to handle requests.
type Server struct {
	h   Handler
	sec SecurityHandler
	baseServer
}

// NewServer creates new Server.
func NewServer(h Handler, sec SecurityHandler, opts ...ServerOption) (*Server, error) {
	s, err := newServerConfig(opts...).baseServer()
	if err != nil {
		return nil, err
	}
	return &Server{
		h:          h,
		sec:        sec,
		baseServer: s,
	}, nil
}
