#!/bin/sh
#
# Ruby Core - Fetch NATS Server Certificates and Generate auth.conf from Vault
#
# Used as the entrypoint for the nats-init container. Fetches server TLS
# certificates and service NKEY public keys from Vault, then writes them to a
# shared Docker volume that the NATS container reads from.
#
# Environment variables:
#   VAULT_ADDR   - Vault address (required, set by compose)
#   VAULT_TOKEN  - Vault token (required, set by compose)
#   CERTS_DIR    - Output directory (default: /certs)
#
# Vault paths:
#   secret/ruby-core/tls/nats-server  — fields: cert, key, ca
#   secret/ruby-core/nats/<service>   — field:  public_key
#

set -eu

CERTS_DIR="${CERTS_DIR:-/certs}"
TLS_PATH="${TLS_PATH:-secret/ruby-core/tls/nats-server}"
NKEY_BASE="${NKEY_BASE:-secret/ruby-core/nats}"
MAX_RETRIES=5
RETRY_DELAY=2

echo "[nats-init] Vault: ${VAULT_ADDR}"

# Wait for Vault to become available
attempt=1
while [ "${attempt}" -le "${MAX_RETRIES}" ]; do
    if vault status >/dev/null 2>&1; then
        echo "[nats-init] Vault is reachable"
        break
    fi
    if [ "${attempt}" -eq "${MAX_RETRIES}" ]; then
        echo "[nats-init] ERROR: Vault not reachable after ${MAX_RETRIES} attempts"
        exit 1
    fi
    echo "[nats-init] Vault not ready, retrying in ${RETRY_DELAY}s (${attempt}/${MAX_RETRIES})..."
    sleep "${RETRY_DELAY}"
    attempt=$((attempt + 1))
done

# Fetch all files into a temp directory first to prevent partial writes
TMP_DIR=$(mktemp -d)
trap 'rm -rf "${TMP_DIR}"' EXIT

# =============================================================================
# TLS Certificates
# =============================================================================

echo "[nats-init] Fetching NATS server certificates from Vault (${TLS_PATH})..."

if ! vault kv get "${TLS_PATH}" >/dev/null 2>&1; then
    echo "[nats-init] ERROR: Secret not found at ${TLS_PATH}"
    echo "[nats-init] Run 'make setup-creds' first (with Vault running and VAULT_TOKEN set)."
    exit 2
fi

vault kv get -field=cert "${TLS_PATH}" > "${TMP_DIR}/server-cert.pem"
vault kv get -field=key  "${TLS_PATH}" > "${TMP_DIR}/server-key.pem"
vault kv get -field=ca   "${TLS_PATH}" > "${TMP_DIR}/ca.pem"

for f in server-cert.pem server-key.pem ca.pem; do
    if [ ! -s "${TMP_DIR}/${f}" ]; then
        echo "[nats-init] ERROR: ${f} is empty after fetch"
        exit 1
    fi
done

chmod 644 "${TMP_DIR}/server-cert.pem" "${TMP_DIR}/ca.pem"
chmod 644 "${TMP_DIR}/server-key.pem"

# =============================================================================
# NKEY Public Keys → auth.conf
# =============================================================================

echo "[nats-init] Fetching service NKEY public keys from Vault..."

fetch_pubkey() {
    service="$1"
    path="${NKEY_BASE}/${service}"
    if ! vault kv get "${path}" >/dev/null 2>&1; then
        echo "[nats-init] ERROR: NKEY secret not found at ${path}"
        echo "[nats-init] Run 'make setup-creds' first."
        exit 2
    fi
    key=$(vault kv get -field=public_key "${path}")
    if [ -z "${key}" ]; then
        echo "[nats-init] ERROR: public_key field empty at ${path}"
        exit 1
    fi
    echo "${key}"
}

PUBKEY_GATEWAY=$(fetch_pubkey gateway)
PUBKEY_ENGINE=$(fetch_pubkey engine)
PUBKEY_NOTIFIER=$(fetch_pubkey notifier)
PUBKEY_PRESENCE=$(fetch_pubkey presence)
PUBKEY_ADMIN=$(fetch_pubkey admin)
PUBKEY_AUDIT_SINK=$(fetch_pubkey audit-sink)
PUBKEY_NAVI_DEV=$(fetch_pubkey navi-dev)
PUBKEY_NAVI_STAGING=$(fetch_pubkey navi-staging)
PUBKEY_NAVI_PROD=$(fetch_pubkey navi-prod)

echo "[nats-init] Generating auth.conf..."

cat > "${TMP_DIR}/auth.conf" <<EOF
# AUTO-GENERATED by nats-init container at startup — do not edit manually.
# Source: Vault NKEY public keys (ADR-0015, ADR-0017)
#
# Subject naming follows ADR-0027: {source}.{class}.{type}[.{id}][.{action}]
# Exception: audit subjects use audit.{source}.{type} to avoid overlap with dlq.>
# Classes: events, commands, audit, metrics, logs

authorization {
  # Default permissions - deny all (defense in depth)
  default_permissions: {
    publish: {
      deny: ">"
    }
    subscribe: {
      deny: ">"
    }
  }

  users: [
    # Gateway service
    # Responsibilities: Ingest HA events, publish to NATS, reconcile state on reconnect
    # Phase 5 additions:
    #   publish  \$JS.API.>         — JetStream API (KV create/bind, stream queries)
    #   publish  \$JS.ACK.>         — Message acknowledgements
    #   publish  \$KV.gateway_state.> — Gateway reconciler state (single-writer, ADR-0002)
    #   subscribe _INBOX.>          — Reply-to subjects for JetStream API responses
    #   subscribe \$KV.config.>     — Read compiled rule config (passlist + critical entities)
    {
      nkey: "${PUBKEY_GATEWAY}"
      permissions: {
        publish: {
          allow: [
            "ha.events.>",
            "audit.ruby_gateway.>",
            "ruby_gateway.metrics.>",
            "gateway.health",
            "\$JS.API.>",
            "\$JS.ACK.>",
            "\$KV.gateway_state.>"
          ]
        }
        subscribe: {
          allow: [
            "ruby_engine.commands.>",
            "_INBOX.>",
            "\$KV.config.>"
          ]
        }
      }
    },

    # Engine service
    # Responsibilities: Process events, evaluate rules, publish commands
    # Phase 3 additions:
    #   publish  \$JS.API.>     — JetStream API (stream/consumer setup, pull requests, KV)
    #   publish  \$JS.ACK.>     — Message acknowledgements to JetStream
    #   publish  \$KV.idempotency.> — Idempotency KV bucket (single-writer, ADR-0002)
    #   publish  dlq.>          — DLQ forwarder routes dead-lettered messages (ADR-0022)
    #   subscribe _INBOX.>      — Reply-to subjects for JetStream API responses
    #   subscribe \$JS.EVENT.ADVISORY.CONSUMER.MAX_DELIVERIES.HA_EVENTS.engine_processor
    #                           — max-delivery advisory triggers DLQ routing (ADR-0022)
    # Phase 5 additions:
    #   publish  \$KV.config.>    — Compiled rule config for gateway (single-writer, ADR-0002)
    #   publish  \$KV.presence.>  — Presence processor state (single-writer, ADR-0002)
    {
      nkey: "${PUBKEY_ENGINE}"
      permissions: {
        publish: {
          allow: [
            "ruby_engine.commands.>",
            "audit.ruby_engine.>",
            "ruby_engine.metrics.>",
            "\$JS.API.>",
            "\$JS.ACK.>",
            "\$KV.idempotency.>",
            "\$KV.config.>",
            "\$KV.presence.>",
            "dlq.>"
          ]
        }
        subscribe: {
          allow: [
            "ha.events.>",
            "gateway.health",
            "_INBOX.>",
            "\$JS.EVENT.ADVISORY.CONSUMER.MAX_DELIVERIES.HA_EVENTS.engine_processor"
          ]
        }
      }
    },

    # Notifier service
    # Responsibilities: Receive notify commands from COMMANDS stream, dispatch push notifications via HA REST API
    # Phase 5 additions:
    #   publish  \$JS.API.>         — JetStream API (consumer create/fetch/bind)
    #   publish  \$JS.ACK.>         — Message acknowledgements
    {
      nkey: "${PUBKEY_NOTIFIER}"
      permissions: {
        publish: {
          allow: [
            "audit.ruby_notifier.>",
            "ruby_notifier.metrics.>",
            "\$JS.API.>",
            "\$JS.ACK.>"
          ]
        }
        subscribe: {
          allow: [
            "ruby_engine.commands.notify.>",
            "_INBOX.>"
          ]
        }
      }
    },

    # Presence service
    # Responsibilities: Multi-source presence fusion; subscribes to HA phone events,
    #   publishes clean presence state events and audit trail.
    {
      nkey: "${PUBKEY_PRESENCE}"
      permissions: {
        publish: {
          allow: [
            "ruby_presence.events.>",
            "audit.ruby_presence.>",
            "ruby_presence.metrics.>",
            "\$JS.API.>",
            "\$JS.ACK.>",
            "\$KV.presence.>",
            "_INBOX.>"
          ]
        }
        subscribe: {
          allow: [
            "ha.events.phone.>",
            "_INBOX.>",
            "\$JS.API.>",
            "\$JS.ACK.>"
          ]
        }
      }
    },

    # Audit-Sink service
    # Responsibilities: Consume all *.audit.> events from AUDIT_EVENTS stream, archive to NDJSON file
    # Principle of least privilege: no publish to business subjects; only JetStream API/ACK
    {
      nkey: "${PUBKEY_AUDIT_SINK}"
      permissions: {
        publish: {
          allow: [
            "\$JS.API.>",
            "\$JS.ACK.>"
          ]
        }
        subscribe: {
          allow: [
            "_INBOX.>"
          ]
        }
      }
    },

    # Navi digest service (dev)
    {
      nkey: "${PUBKEY_NAVI_DEV}"
      permissions: {
        publish: {
          allow: ["navi.dev.>", "audit.navi.>", "\$JS.API.>", "\$JS.ACK.>"]
        }
        subscribe: {
          allow: ["navi.dev.>", "_INBOX.>"]
        }
      }
    },

    # Navi digest service (staging)
    {
      nkey: "${PUBKEY_NAVI_STAGING}"
      permissions: {
        publish: {
          allow: ["navi.staging.>", "audit.navi.>", "\$JS.API.>", "\$JS.ACK.>"]
        }
        subscribe: {
          allow: ["navi.staging.>", "_INBOX.>"]
        }
      }
    },

    # Navi digest service (prod)
    {
      nkey: "${PUBKEY_NAVI_PROD}"
      permissions: {
        publish: {
          allow: ["navi.prod.>", "audit.navi.>", "\$JS.API.>", "\$JS.ACK.>"]
        }
        subscribe: {
          allow: ["navi.prod.>", "_INBOX.>"]
        }
      }
    },

    # Admin/operator account (for debugging and maintenance)
    {
      nkey: "${PUBKEY_ADMIN}"
      permissions: {
        publish: {
          allow: ">"
        }
        subscribe: {
          allow: ">"
        }
      }
    }
  ]
}
EOF

if [ ! -s "${TMP_DIR}/auth.conf" ]; then
    echo "[nats-init] ERROR: auth.conf is empty after generation"
    exit 1
fi

# =============================================================================
# Atomic write to shared volume
# =============================================================================

mv "${TMP_DIR}/server-cert.pem" "${CERTS_DIR}/server-cert.pem"
mv "${TMP_DIR}/server-key.pem"  "${CERTS_DIR}/server-key.pem"
mv "${TMP_DIR}/ca.pem"          "${CERTS_DIR}/ca.pem"
mv "${TMP_DIR}/auth.conf"       "${CERTS_DIR}/auth.conf"

echo "[nats-init] Certificates and auth.conf written to ${CERTS_DIR}"
echo "[nats-init] Done."
