// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: calendar.sql

package store

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const deleteEvent = `-- name: DeleteEvent :exec
DELETE FROM calendar_event WHERE google_event_id = $1
`

func (q *Queries) DeleteEvent(ctx context.Context, googleEventID string) error {
	_, err := q.db.Exec(ctx, deleteEvent, googleEventID)
	return err
}

const getEvent = `-- name: GetEvent :one
SELECT google_event_id, ical_uid, summary, start_date, start_datetime, start_timezone, end_date, end_datetime, end_timezone, all_day, start_utc, end_utc, recurrence, recurring_event_id, original_start_date, original_start_datetime, original_start_timezone, location, description, calendar_id, status, etag, sequence, raw, synced_at FROM calendar_event WHERE google_event_id = $1
`

func (q *Queries) GetEvent(ctx context.Context, googleEventID string) (*CalendarEvent, error) {
	row := q.db.QueryRow(ctx, getEvent, googleEventID)
	var i CalendarEvent
	err := row.Scan(
		&i.GoogleEventID,
		&i.IcalUid,
		&i.Summary,
		&i.StartDate,
		&i.StartDatetime,
		&i.StartTimezone,
		&i.EndDate,
		&i.EndDatetime,
		&i.EndTimezone,
		&i.AllDay,
		&i.StartUtc,
		&i.EndUtc,
		&i.Recurrence,
		&i.RecurringEventID,
		&i.OriginalStartDate,
		&i.OriginalStartDatetime,
		&i.OriginalStartTimezone,
		&i.Location,
		&i.Description,
		&i.CalendarID,
		&i.Status,
		&i.Etag,
		&i.Sequence,
		&i.Raw,
		&i.SyncedAt,
	)
	return &i, err
}

const listOverrides = `-- name: ListOverrides :many
SELECT google_event_id, ical_uid, summary, start_date, start_datetime, start_timezone, end_date, end_datetime, end_timezone, all_day, start_utc, end_utc, recurrence, recurring_event_id, original_start_date, original_start_datetime, original_start_timezone, location, description, calendar_id, status, etag, sequence, raw, synced_at FROM calendar_event
WHERE recurring_event_id IS NOT NULL
ORDER BY recurring_event_id, start_utc
`

// ListOverrides returns every override/cancelled child across all series; the
// caller groups them by recurring_event_id and subtracts/applies during expansion.
func (q *Queries) ListOverrides(ctx context.Context) ([]*CalendarEvent, error) {
	rows, err := q.db.Query(ctx, listOverrides)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []*CalendarEvent
	for rows.Next() {
		var i CalendarEvent
		if err := rows.Scan(
			&i.GoogleEventID,
			&i.IcalUid,
			&i.Summary,
			&i.StartDate,
			&i.StartDatetime,
			&i.StartTimezone,
			&i.EndDate,
			&i.EndDatetime,
			&i.EndTimezone,
			&i.AllDay,
			&i.StartUtc,
			&i.EndUtc,
			&i.Recurrence,
			&i.RecurringEventID,
			&i.OriginalStartDate,
			&i.OriginalStartDatetime,
			&i.OriginalStartTimezone,
			&i.Location,
			&i.Description,
			&i.CalendarID,
			&i.Status,
			&i.Etag,
			&i.Sequence,
			&i.Raw,
			&i.SyncedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRecurringMasters = `-- name: ListRecurringMasters :many
SELECT google_event_id, ical_uid, summary, start_date, start_datetime, start_timezone, end_date, end_datetime, end_timezone, all_day, start_utc, end_utc, recurrence, recurring_event_id, original_start_date, original_start_datetime, original_start_timezone, location, description, calendar_id, status, etag, sequence, raw, synced_at FROM calendar_event
WHERE recurrence IS NOT NULL
  AND status <> 'cancelled'
ORDER BY start_utc
`

// ListRecurringMasters returns every recurring series master (no range filter —
// expansion decides which occurrences fall in the window).
func (q *Queries) ListRecurringMasters(ctx context.Context) ([]*CalendarEvent, error) {
	rows, err := q.db.Query(ctx, listRecurringMasters)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []*CalendarEvent
	for rows.Next() {
		var i CalendarEvent
		if err := rows.Scan(
			&i.GoogleEventID,
			&i.IcalUid,
			&i.Summary,
			&i.StartDate,
			&i.StartDatetime,
			&i.StartTimezone,
			&i.EndDate,
			&i.EndDatetime,
			&i.EndTimezone,
			&i.AllDay,
			&i.StartUtc,
			&i.EndUtc,
			&i.Recurrence,
			&i.RecurringEventID,
			&i.OriginalStartDate,
			&i.OriginalStartDatetime,
			&i.OriginalStartTimezone,
			&i.Location,
			&i.Description,
			&i.CalendarID,
			&i.Status,
			&i.Etag,
			&i.Sequence,
			&i.Raw,
			&i.SyncedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSingleEventsInRange = `-- name: ListSingleEventsInRange :many
SELECT google_event_id, ical_uid, summary, start_date, start_datetime, start_timezone, end_date, end_datetime, end_timezone, all_day, start_utc, end_utc, recurrence, recurring_event_id, original_start_date, original_start_datetime, original_start_timezone, location, description, calendar_id, status, etag, sequence, raw, synced_at FROM calendar_event
WHERE recurrence IS NULL
  AND recurring_event_id IS NULL
  AND status <> 'cancelled'
  AND end_utc > $1
  AND start_utc < $2
ORDER BY start_utc
`

type ListSingleEventsInRangeParams struct {
	RangeStart pgtype.Timestamptz
	RangeEnd   pgtype.Timestamptz
}

// ListSingleEventsInRange returns non-recurring, non-override, non-cancelled events
// whose [start_utc, end_utc) overlaps the requested window.
func (q *Queries) ListSingleEventsInRange(ctx context.Context, arg *ListSingleEventsInRangeParams) ([]*CalendarEvent, error) {
	rows, err := q.db.Query(ctx, listSingleEventsInRange, arg.RangeStart, arg.RangeEnd)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []*CalendarEvent
	for rows.Next() {
		var i CalendarEvent
		if err := rows.Scan(
			&i.GoogleEventID,
			&i.IcalUid,
			&i.Summary,
			&i.StartDate,
			&i.StartDatetime,
			&i.StartTimezone,
			&i.EndDate,
			&i.EndDatetime,
			&i.EndTimezone,
			&i.AllDay,
			&i.StartUtc,
			&i.EndUtc,
			&i.Recurrence,
			&i.RecurringEventID,
			&i.OriginalStartDate,
			&i.OriginalStartDatetime,
			&i.OriginalStartTimezone,
			&i.Location,
			&i.Description,
			&i.CalendarID,
			&i.Status,
			&i.Etag,
			&i.Sequence,
			&i.Raw,
			&i.SyncedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertEvent = `-- name: UpsertEvent :exec
INSERT INTO calendar_event (
    google_event_id, ical_uid, summary,
    start_date, start_datetime, start_timezone,
    end_date, end_datetime, end_timezone, all_day,
    start_utc, end_utc,
    recurrence, recurring_event_id,
    original_start_date, original_start_datetime, original_start_timezone,
    location, description, calendar_id, status, etag, sequence, raw, synced_at
) VALUES (
    $1, $2, $3,
    $4, $5, $6,
    $7, $8, $9, $10,
    $11, $12,
    $13, $14,
    $15, $16, $17,
    $18, $19, $20, $21, $22, $23, $24, now()
)
ON CONFLICT (google_event_id) DO UPDATE SET
    ical_uid = EXCLUDED.ical_uid,
    summary = EXCLUDED.summary,
    start_date = EXCLUDED.start_date,
    start_datetime = EXCLUDED.start_datetime,
    start_timezone = EXCLUDED.start_timezone,
    end_date = EXCLUDED.end_date,
    end_datetime = EXCLUDED.end_datetime,
    end_timezone = EXCLUDED.end_timezone,
    all_day = EXCLUDED.all_day,
    start_utc = EXCLUDED.start_utc,
    end_utc = EXCLUDED.end_utc,
    recurrence = EXCLUDED.recurrence,
    recurring_event_id = EXCLUDED.recurring_event_id,
    original_start_date = EXCLUDED.original_start_date,
    original_start_datetime = EXCLUDED.original_start_datetime,
    original_start_timezone = EXCLUDED.original_start_timezone,
    location = EXCLUDED.location,
    description = EXCLUDED.description,
    calendar_id = EXCLUDED.calendar_id,
    status = EXCLUDED.status,
    etag = EXCLUDED.etag,
    sequence = EXCLUDED.sequence,
    raw = EXCLUDED.raw,
    synced_at = now()
`

type UpsertEventParams struct {
	GoogleEventID         string
	IcalUid               pgtype.Text
	Summary               pgtype.Text
	StartDate             pgtype.Date
	StartDatetime         pgtype.Timestamptz
	StartTimezone         pgtype.Text
	EndDate               pgtype.Date
	EndDatetime           pgtype.Timestamptz
	EndTimezone           pgtype.Text
	AllDay                bool
	StartUtc              pgtype.Timestamptz
	EndUtc                pgtype.Timestamptz
	Recurrence            []string
	RecurringEventID      pgtype.Text
	OriginalStartDate     pgtype.Date
	OriginalStartDatetime pgtype.Timestamptz
	OriginalStartTimezone pgtype.Text
	Location              pgtype.Text
	Description           pgtype.Text
	CalendarID            string
	Status                string
	Etag                  string
	Sequence              int32
	Raw                   []byte
}

func (q *Queries) UpsertEvent(ctx context.Context, arg *UpsertEventParams) error {
	_, err := q.db.Exec(ctx, upsertEvent,
		arg.GoogleEventID,
		arg.IcalUid,
		arg.Summary,
		arg.StartDate,
		arg.StartDatetime,
		arg.StartTimezone,
		arg.EndDate,
		arg.EndDatetime,
		arg.EndTimezone,
		arg.AllDay,
		arg.StartUtc,
		arg.EndUtc,
		arg.Recurrence,
		arg.RecurringEventID,
		arg.OriginalStartDate,
		arg.OriginalStartDatetime,
		arg.OriginalStartTimezone,
		arg.Location,
		arg.Description,
		arg.CalendarID,
		arg.Status,
		arg.Etag,
		arg.Sequence,
		arg.Raw,
	)
	return err
}
