// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package store

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type CalendarEvent struct {
	GoogleEventID         string
	IcalUid               pgtype.Text
	Summary               pgtype.Text
	StartDate             pgtype.Date
	StartDatetime         pgtype.Timestamptz
	StartTimezone         pgtype.Text
	EndDate               pgtype.Date
	EndDatetime           pgtype.Timestamptz
	EndTimezone           pgtype.Text
	AllDay                bool
	StartUtc              pgtype.Timestamptz
	EndUtc                pgtype.Timestamptz
	Recurrence            []string
	RecurringEventID      pgtype.Text
	OriginalStartDate     pgtype.Date
	OriginalStartDatetime pgtype.Timestamptz
	OriginalStartTimezone pgtype.Text
	Location              pgtype.Text
	Description           pgtype.Text
	CalendarID            string
	Status                string
	Etag                  string
	Sequence              int32
	Raw                   []byte
	SyncedAt              pgtype.Timestamptz
}

type ChildcareProvider struct {
	ID           pgtype.UUID
	DisplayName  string
	PersonID     pgtype.UUID
	Relationship pgtype.Text
	Archived     bool
	CreatedAt    pgtype.Timestamptz
}

type DirectoryPerson struct {
	ID               pgtype.UUID
	DisplayName      string
	Kind             string
	HaPersonEntityID pgtype.Text
	Email            pgtype.Text
	Family           pgtype.Text
	Color            pgtype.Text
	Active           bool
	CreatedAt        pgtype.Timestamptz
}

type EventChildcare struct {
	ID            pgtype.UUID
	GoogleEventID string
	ProviderID    pgtype.UUID
	CreatedAt     pgtype.Timestamptz
}

type EventSubject struct {
	ID            pgtype.UUID
	GoogleEventID string
	PersonID      pgtype.UUID
	CreatedAt     pgtype.Timestamptz
}

type SyncState struct {
	CalendarID       string
	SyncToken        pgtype.Text
	LastSyncedAt     pgtype.Timestamptz
	LastFullResyncAt pgtype.Timestamptz
	UpdatedAt        pgtype.Timestamptz
}
