// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: overlay.sql

package store

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const archiveProvider = `-- name: ArchiveProvider :exec
UPDATE childcare_provider SET archived = true WHERE id = $1
`

// ArchiveProvider soft-deletes (delete = archive, preserving frequency history).
func (q *Queries) ArchiveProvider(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, archiveProvider, id)
	return err
}

const deactivatePerson = `-- name: DeactivatePerson :exec
UPDATE directory_person SET active = false WHERE id = $1
`

// DeactivatePerson soft-deletes a person (#155 §3) — the row is retained so historical
// event associations still resolve.
func (q *Queries) DeactivatePerson(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deactivatePerson, id)
	return err
}

const deleteEventChildcare = `-- name: DeleteEventChildcare :exec
DELETE FROM event_childcare WHERE google_event_id = $1
`

func (q *Queries) DeleteEventChildcare(ctx context.Context, googleEventID string) error {
	_, err := q.db.Exec(ctx, deleteEventChildcare, googleEventID)
	return err
}

const deleteEventSubjects = `-- name: DeleteEventSubjects :exec

DELETE FROM event_subject WHERE google_event_id = $1
`

// ============================ associations ============================
func (q *Queries) DeleteEventSubjects(ctx context.Context, googleEventID string) error {
	_, err := q.db.Exec(ctx, deleteEventSubjects, googleEventID)
	return err
}

const getPersonByEmail = `-- name: GetPersonByEmail :one
SELECT id, display_name, kind, ha_person_entity_id, email, family, color, active, created_at FROM directory_person WHERE lower(email) = lower($1) LIMIT 1
`

func (q *Queries) GetPersonByEmail(ctx context.Context, email string) (*DirectoryPerson, error) {
	row := q.db.QueryRow(ctx, getPersonByEmail, email)
	var i DirectoryPerson
	err := row.Scan(
		&i.ID,
		&i.DisplayName,
		&i.Kind,
		&i.HaPersonEntityID,
		&i.Email,
		&i.Family,
		&i.Color,
		&i.Active,
		&i.CreatedAt,
	)
	return &i, err
}

const insertEventChildcare = `-- name: InsertEventChildcare :exec
INSERT INTO event_childcare (google_event_id, provider_id)
VALUES ($1, $2)
ON CONFLICT (google_event_id, provider_id) DO NOTHING
`

type InsertEventChildcareParams struct {
	GoogleEventID string
	ProviderID    pgtype.UUID
}

func (q *Queries) InsertEventChildcare(ctx context.Context, arg *InsertEventChildcareParams) error {
	_, err := q.db.Exec(ctx, insertEventChildcare, arg.GoogleEventID, arg.ProviderID)
	return err
}

const insertEventSubject = `-- name: InsertEventSubject :exec
INSERT INTO event_subject (google_event_id, person_id)
VALUES ($1, $2)
ON CONFLICT (google_event_id, person_id) DO NOTHING
`

type InsertEventSubjectParams struct {
	GoogleEventID string
	PersonID      pgtype.UUID
}

func (q *Queries) InsertEventSubject(ctx context.Context, arg *InsertEventSubjectParams) error {
	_, err := q.db.Exec(ctx, insertEventSubject, arg.GoogleEventID, arg.PersonID)
	return err
}

const listActivePeople = `-- name: ListActivePeople :many

SELECT id, display_name, kind, ha_person_entity_id, email, family, color, active, created_at FROM directory_person WHERE active ORDER BY display_name
`

// ============================ directory_person ============================
func (q *Queries) ListActivePeople(ctx context.Context) ([]*DirectoryPerson, error) {
	rows, err := q.db.Query(ctx, listActivePeople)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []*DirectoryPerson
	for rows.Next() {
		var i DirectoryPerson
		if err := rows.Scan(
			&i.ID,
			&i.DisplayName,
			&i.Kind,
			&i.HaPersonEntityID,
			&i.Email,
			&i.Family,
			&i.Color,
			&i.Active,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listActiveProviders = `-- name: ListActiveProviders :many

SELECT id, display_name, person_id, relationship, archived, created_at FROM childcare_provider WHERE NOT archived ORDER BY display_name
`

// ============================ childcare_provider ============================
func (q *Queries) ListActiveProviders(ctx context.Context) ([]*ChildcareProvider, error) {
	rows, err := q.db.Query(ctx, listActiveProviders)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []*ChildcareProvider
	for rows.Next() {
		var i ChildcareProvider
		if err := rows.Scan(
			&i.ID,
			&i.DisplayName,
			&i.PersonID,
			&i.Relationship,
			&i.Archived,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAllPersonEmails = `-- name: ListAllPersonEmails :many
SELECT person_id, email FROM person_email
`

type ListAllPersonEmailsRow struct {
	PersonID pgtype.UUID
	Email    string
}

// ListAllPersonEmails returns every alias email -> person mapping for the read index.
func (q *Queries) ListAllPersonEmails(ctx context.Context) ([]*ListAllPersonEmailsRow, error) {
	rows, err := q.db.Query(ctx, listAllPersonEmails)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []*ListAllPersonEmailsRow
	for rows.Next() {
		var i ListAllPersonEmailsRow
		if err := rows.Scan(&i.PersonID, &i.Email); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listChildcareForEvents = `-- name: ListChildcareForEvents :many
SELECT google_event_id, provider_id FROM event_childcare
WHERE google_event_id = ANY($1::text[])
`

type ListChildcareForEventsRow struct {
	GoogleEventID string
	ProviderID    pgtype.UUID
}

// ListChildcareForEvents returns childcare associations for a set of events.
func (q *Queries) ListChildcareForEvents(ctx context.Context, eventIds []string) ([]*ListChildcareForEventsRow, error) {
	rows, err := q.db.Query(ctx, listChildcareForEvents, eventIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []*ListChildcareForEventsRow
	for rows.Next() {
		var i ListChildcareForEventsRow
		if err := rows.Scan(&i.GoogleEventID, &i.ProviderID); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPeopleByIDs = `-- name: ListPeopleByIDs :many
SELECT id, display_name, kind, ha_person_entity_id, email, family, color, active, created_at FROM directory_person WHERE id = ANY($1::uuid[])
`

func (q *Queries) ListPeopleByIDs(ctx context.Context, ids []pgtype.UUID) ([]*DirectoryPerson, error) {
	rows, err := q.db.Query(ctx, listPeopleByIDs, ids)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []*DirectoryPerson
	for rows.Next() {
		var i DirectoryPerson
		if err := rows.Scan(
			&i.ID,
			&i.DisplayName,
			&i.Kind,
			&i.HaPersonEntityID,
			&i.Email,
			&i.Family,
			&i.Color,
			&i.Active,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listProviderEvents = `-- name: ListProviderEvents :many
SELECT ec.provider_id, ce.google_event_id, ce.ical_uid, ce.summary, ce.start_date, ce.start_datetime, ce.start_timezone, ce.end_date, ce.end_datetime, ce.end_timezone, ce.all_day, ce.start_utc, ce.end_utc, ce.recurrence, ce.recurring_event_id, ce.original_start_date, ce.original_start_datetime, ce.original_start_timezone, ce.location, ce.description, ce.calendar_id, ce.status, ce.etag, ce.sequence, ce.raw, ce.synced_at
FROM event_childcare ec
JOIN calendar_event ce ON ce.google_event_id = ec.google_event_id
JOIN childcare_provider p ON p.id = ec.provider_id
WHERE NOT p.archived AND ce.status <> 'cancelled'
`

type ListProviderEventsRow struct {
	ProviderID            pgtype.UUID
	GoogleEventID         string
	IcalUid               pgtype.Text
	Summary               pgtype.Text
	StartDate             pgtype.Date
	StartDatetime         pgtype.Timestamptz
	StartTimezone         pgtype.Text
	EndDate               pgtype.Date
	EndDatetime           pgtype.Timestamptz
	EndTimezone           pgtype.Text
	AllDay                bool
	StartUtc              pgtype.Timestamptz
	EndUtc                pgtype.Timestamptz
	Recurrence            []string
	RecurringEventID      pgtype.Text
	OriginalStartDate     pgtype.Date
	OriginalStartDatetime pgtype.Timestamptz
	OriginalStartTimezone pgtype.Text
	Location              pgtype.Text
	Description           pgtype.Text
	CalendarID            string
	Status                string
	Etag                  string
	Sequence              int32
	Raw                   []byte
	SyncedAt              pgtype.Timestamptz
}

// ListProviderEvents returns, for every non-archived provider, the calendar_event
// rows it is associated with — the input to per-occurrence suggestion ranking.
func (q *Queries) ListProviderEvents(ctx context.Context) ([]*ListProviderEventsRow, error) {
	rows, err := q.db.Query(ctx, listProviderEvents)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []*ListProviderEventsRow
	for rows.Next() {
		var i ListProviderEventsRow
		if err := rows.Scan(
			&i.ProviderID,
			&i.GoogleEventID,
			&i.IcalUid,
			&i.Summary,
			&i.StartDate,
			&i.StartDatetime,
			&i.StartTimezone,
			&i.EndDate,
			&i.EndDatetime,
			&i.EndTimezone,
			&i.AllDay,
			&i.StartUtc,
			&i.EndUtc,
			&i.Recurrence,
			&i.RecurringEventID,
			&i.OriginalStartDate,
			&i.OriginalStartDatetime,
			&i.OriginalStartTimezone,
			&i.Location,
			&i.Description,
			&i.CalendarID,
			&i.Status,
			&i.Etag,
			&i.Sequence,
			&i.Raw,
			&i.SyncedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listProvidersByIDs = `-- name: ListProvidersByIDs :many
SELECT id, display_name, person_id, relationship, archived, created_at FROM childcare_provider WHERE id = ANY($1::uuid[])
`

func (q *Queries) ListProvidersByIDs(ctx context.Context, ids []pgtype.UUID) ([]*ChildcareProvider, error) {
	rows, err := q.db.Query(ctx, listProvidersByIDs, ids)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []*ChildcareProvider
	for rows.Next() {
		var i ChildcareProvider
		if err := rows.Scan(
			&i.ID,
			&i.DisplayName,
			&i.PersonID,
			&i.Relationship,
			&i.Archived,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSubjectsForEvents = `-- name: ListSubjectsForEvents :many
SELECT google_event_id, person_id FROM event_subject
WHERE google_event_id = ANY($1::text[])
`

type ListSubjectsForEventsRow struct {
	GoogleEventID string
	PersonID      pgtype.UUID
}

// ListSubjectsForEvents returns subject associations for a set of events.
func (q *Queries) ListSubjectsForEvents(ctx context.Context, eventIds []string) ([]*ListSubjectsForEventsRow, error) {
	rows, err := q.db.Query(ctx, listSubjectsForEvents, eventIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []*ListSubjectsForEventsRow
	for rows.Next() {
		var i ListSubjectsForEventsRow
		if err := rows.Scan(&i.GoogleEventID, &i.PersonID); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertPerson = `-- name: UpsertPerson :exec
INSERT INTO directory_person (id, display_name, kind, ha_person_entity_id, email, family, color, active)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
ON CONFLICT (id) DO UPDATE SET
    display_name = EXCLUDED.display_name,
    kind = EXCLUDED.kind,
    ha_person_entity_id = EXCLUDED.ha_person_entity_id,
    email = EXCLUDED.email,
    family = EXCLUDED.family,
    color = EXCLUDED.color,
    active = EXCLUDED.active
`

type UpsertPersonParams struct {
	ID               pgtype.UUID
	DisplayName      string
	Kind             string
	HaPersonEntityID pgtype.Text
	Email            pgtype.Text
	Family           pgtype.Text
	Color            pgtype.Text
	Active           bool
}

func (q *Queries) UpsertPerson(ctx context.Context, arg *UpsertPersonParams) error {
	_, err := q.db.Exec(ctx, upsertPerson,
		arg.ID,
		arg.DisplayName,
		arg.Kind,
		arg.HaPersonEntityID,
		arg.Email,
		arg.Family,
		arg.Color,
		arg.Active,
	)
	return err
}

const upsertPersonEmail = `-- name: UpsertPersonEmail :exec


INSERT INTO person_email (person_id, email)
VALUES ($1, $2)
ON CONFLICT (lower(email)) DO UPDATE SET person_id = EXCLUDED.person_id
`

type UpsertPersonEmailParams struct {
	PersonID pgtype.UUID
	Email    string
}

// ============================ person_email ============================
// person_email holds a directory person's alias / secondary addresses (#133); the
// primary stays on directory_person.email. Attendee reconciliation matches either source.
func (q *Queries) UpsertPersonEmail(ctx context.Context, arg *UpsertPersonEmailParams) error {
	_, err := q.db.Exec(ctx, upsertPersonEmail, arg.PersonID, arg.Email)
	return err
}

const upsertProvider = `-- name: UpsertProvider :exec
INSERT INTO childcare_provider (id, display_name, person_id, relationship, archived)
VALUES ($1, $2, $3, $4, $5)
ON CONFLICT (id) DO UPDATE SET
    display_name = EXCLUDED.display_name,
    person_id = EXCLUDED.person_id,
    relationship = EXCLUDED.relationship,
    archived = EXCLUDED.archived
`

type UpsertProviderParams struct {
	ID           pgtype.UUID
	DisplayName  string
	PersonID     pgtype.UUID
	Relationship pgtype.Text
	Archived     bool
}

func (q *Queries) UpsertProvider(ctx context.Context, arg *UpsertProviderParams) error {
	_, err := q.db.Exec(ctx, upsertProvider,
		arg.ID,
		arg.DisplayName,
		arg.PersonID,
		arg.Relationship,
		arg.Archived,
	)
	return err
}
