// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: sync_state.sql

package store

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getSyncState = `-- name: GetSyncState :one
SELECT calendar_id, sync_token, last_synced_at, last_full_resync_at, updated_at FROM sync_state WHERE calendar_id = $1
`

func (q *Queries) GetSyncState(ctx context.Context, calendarID string) (*SyncState, error) {
	row := q.db.QueryRow(ctx, getSyncState, calendarID)
	var i SyncState
	err := row.Scan(
		&i.CalendarID,
		&i.SyncToken,
		&i.LastSyncedAt,
		&i.LastFullResyncAt,
		&i.UpdatedAt,
	)
	return &i, err
}

const markFullResync = `-- name: MarkFullResync :exec
INSERT INTO sync_state (calendar_id, sync_token, last_full_resync_at, updated_at)
VALUES ($1, NULL, now(), now())
ON CONFLICT (calendar_id) DO UPDATE SET
    sync_token = NULL,
    last_full_resync_at = now(),
    updated_at = now()
`

// MarkFullResync clears the sync token (e.g. on a 410 Gone) and stamps the full
// resync time. The next pass pages through from scratch and records a fresh token.
func (q *Queries) MarkFullResync(ctx context.Context, calendarID string) error {
	_, err := q.db.Exec(ctx, markFullResync, calendarID)
	return err
}

const upsertSyncToken = `-- name: UpsertSyncToken :exec
INSERT INTO sync_state (calendar_id, sync_token, last_synced_at, updated_at)
VALUES ($1, $2, now(), now())
ON CONFLICT (calendar_id) DO UPDATE SET
    sync_token = EXCLUDED.sync_token,
    last_synced_at = now(),
    updated_at = now()
`

type UpsertSyncTokenParams struct {
	CalendarID string
	SyncToken  pgtype.Text
}

// UpsertSyncToken records the latest nextSyncToken after a successful sync pass.
func (q *Queries) UpsertSyncToken(ctx context.Context, arg *UpsertSyncTokenParams) error {
	_, err := q.db.Exec(ctx, upsertSyncToken, arg.CalendarID, arg.SyncToken)
	return err
}
