// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: caretakers.sql

package store

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getActiveCaretakers = `-- name: GetActiveCaretakers :many
SELECT ha_user_id, display_name, notify_service
FROM caretakers
WHERE deleted_at IS NULL
  AND is_caretaker = true
  AND notify_service IS NOT NULL
ORDER BY display_name
`

type GetActiveCaretakersRow struct {
	HaUserID      string
	DisplayName   string
	NotifyService pgtype.Text
}

func (q *Queries) GetActiveCaretakers(ctx context.Context) ([]*GetActiveCaretakersRow, error) {
	rows, err := q.db.Query(ctx, getActiveCaretakers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []*GetActiveCaretakersRow
	for rows.Next() {
		var i GetActiveCaretakersRow
		if err := rows.Scan(&i.HaUserID, &i.DisplayName, &i.NotifyService); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getAllCaretakers = `-- name: GetAllCaretakers :many
SELECT ha_user_id, display_name, username, is_caretaker, notify_service
FROM caretakers
WHERE deleted_at IS NULL
ORDER BY display_name
`

type GetAllCaretakersRow struct {
	HaUserID      string
	DisplayName   string
	Username      string
	IsCaretaker   bool
	NotifyService pgtype.Text
}

func (q *Queries) GetAllCaretakers(ctx context.Context) ([]*GetAllCaretakersRow, error) {
	rows, err := q.db.Query(ctx, getAllCaretakers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []*GetAllCaretakersRow
	for rows.Next() {
		var i GetAllCaretakersRow
		if err := rows.Scan(
			&i.HaUserID,
			&i.DisplayName,
			&i.Username,
			&i.IsCaretaker,
			&i.NotifyService,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getCaretakerHAUserIDs = `-- name: GetCaretakerHAUserIDs :many
SELECT ha_user_id FROM caretakers
WHERE deleted_at IS NULL
`

func (q *Queries) GetCaretakerHAUserIDs(ctx context.Context) ([]string, error) {
	rows, err := q.db.Query(ctx, getCaretakerHAUserIDs)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var ha_user_id string
		if err := rows.Scan(&ha_user_id); err != nil {
			return nil, err
		}
		items = append(items, ha_user_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const softDeleteCaretaker = `-- name: SoftDeleteCaretaker :exec
UPDATE caretakers
SET deleted_at = NOW(), updated_at = NOW()
WHERE ha_user_id = $1
  AND deleted_at IS NULL
`

func (q *Queries) SoftDeleteCaretaker(ctx context.Context, haUserID string) error {
	_, err := q.db.Exec(ctx, softDeleteCaretaker, haUserID)
	return err
}

const updateCaretakerStatus = `-- name: UpdateCaretakerStatus :exec
UPDATE caretakers
SET is_caretaker = $1, updated_at = NOW()
WHERE ha_user_id = $2
  AND deleted_at IS NULL
`

type UpdateCaretakerStatusParams struct {
	IsCaretaker bool
	HaUserID    string
}

func (q *Queries) UpdateCaretakerStatus(ctx context.Context, arg *UpdateCaretakerStatusParams) error {
	_, err := q.db.Exec(ctx, updateCaretakerStatus, arg.IsCaretaker, arg.HaUserID)
	return err
}

const upsertCaretaker = `-- name: UpsertCaretaker :exec
INSERT INTO caretakers (id, ha_user_id, display_name, username, notify_service, updated_at)
VALUES (gen_random_uuid(), $1, $2, $3, $4, NOW())
ON CONFLICT (ha_user_id) DO UPDATE
    SET display_name   = EXCLUDED.display_name,
        username       = EXCLUDED.username,
        notify_service = EXCLUDED.notify_service,
        deleted_at     = NULL,
        updated_at     = NOW()
`

type UpsertCaretakerParams struct {
	HaUserID      string
	DisplayName   string
	Username      string
	NotifyService pgtype.Text
}

func (q *Queries) UpsertCaretaker(ctx context.Context, arg *UpsertCaretakerParams) error {
	_, err := q.db.Exec(ctx, upsertCaretaker,
		arg.HaUserID,
		arg.DisplayName,
		arg.Username,
		arg.NotifyService,
	)
	return err
}
