// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: config.sql

package store

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getConfig = `-- name: GetConfig :one
SELECT value, updated_at FROM ada_config
WHERE key = $1
`

type GetConfigRow struct {
	Value     string
	UpdatedAt pgtype.Timestamptz
}

func (q *Queries) GetConfig(ctx context.Context, key string) (*GetConfigRow, error) {
	row := q.db.QueryRow(ctx, getConfig, key)
	var i GetConfigRow
	err := row.Scan(&i.Value, &i.UpdatedAt)
	return &i, err
}

const upsertConfig = `-- name: UpsertConfig :exec
INSERT INTO ada_config (key, value, updated_at)
VALUES ($1, $2, NOW())
ON CONFLICT (key) DO UPDATE
    SET value      = EXCLUDED.value,
        updated_at = EXCLUDED.updated_at
`

type UpsertConfigParams struct {
	Key   string
	Value string
}

func (q *Queries) UpsertConfig(ctx context.Context, arg *UpsertConfigParams) error {
	_, err := q.db.Exec(ctx, upsertConfig, arg.Key, arg.Value)
	return err
}
