// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: diapers.sql

package store

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getLast24hDiapers = `-- name: GetLast24hDiapers :many
SELECT id, timestamp, type
FROM diapers
WHERE deleted_at IS NULL
  AND timestamp >= NOW() - INTERVAL '24 hours'
ORDER BY timestamp DESC
`

type GetLast24hDiapersRow struct {
	ID        pgtype.UUID
	Timestamp pgtype.Timestamptz
	Type      string
}

// Returns all diaper events in the last 24 hours ordered newest-first.
func (q *Queries) GetLast24hDiapers(ctx context.Context) ([]*GetLast24hDiapersRow, error) {
	rows, err := q.db.Query(ctx, getLast24hDiapers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []*GetLast24hDiapersRow
	for rows.Next() {
		var i GetLast24hDiapersRow
		if err := rows.Scan(&i.ID, &i.Timestamp, &i.Type); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getLastDiaper = `-- name: GetLastDiaper :one
SELECT timestamp, type FROM diapers
WHERE deleted_at IS NULL
ORDER BY timestamp DESC LIMIT 1
`

type GetLastDiaperRow struct {
	Timestamp pgtype.Timestamptz
	Type      string
}

func (q *Queries) GetLastDiaper(ctx context.Context) (*GetLastDiaperRow, error) {
	row := q.db.QueryRow(ctx, getLastDiaper)
	var i GetLastDiaperRow
	err := row.Scan(&i.Timestamp, &i.Type)
	return &i, err
}

const getTodayDiaperAggregates = `-- name: GetTodayDiaperAggregates :one
SELECT
    COUNT(*)::int                                        AS total,
    COUNT(*) FILTER (WHERE type = 'wet')::int            AS wet,
    COUNT(*) FILTER (WHERE type = 'dirty')::int          AS dirty,
    COUNT(*) FILTER (WHERE type = 'mixed')::int           AS mixed
FROM diapers
WHERE deleted_at IS NULL
  AND timestamp >= NOW()::date
`

type GetTodayDiaperAggregatesRow struct {
	Total int32
	Wet   int32
	Dirty int32
	Mixed int32
}

func (q *Queries) GetTodayDiaperAggregates(ctx context.Context) (*GetTodayDiaperAggregatesRow, error) {
	row := q.db.QueryRow(ctx, getTodayDiaperAggregates)
	var i GetTodayDiaperAggregatesRow
	err := row.Scan(
		&i.Total,
		&i.Wet,
		&i.Dirty,
		&i.Mixed,
	)
	return &i, err
}

const insertDiaper = `-- name: InsertDiaper :exec
INSERT INTO diapers (timestamp, type, logged_by)
VALUES ($1, $2, $3)
`

type InsertDiaperParams struct {
	Timestamp pgtype.Timestamptz
	Type      string
	LoggedBy  string
}

func (q *Queries) InsertDiaper(ctx context.Context, arg *InsertDiaperParams) error {
	_, err := q.db.Exec(ctx, insertDiaper, arg.Timestamp, arg.Type, arg.LoggedBy)
	return err
}
