// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: emergency.sql

package store

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const listEmergencyRows = `-- name: ListEmergencyRows :many
SELECT id, sort_order, type, label, name, phone, address, field_key
FROM emergency_rows
WHERE deleted_at IS NULL
ORDER BY sort_order, created_at
`

type ListEmergencyRowsRow struct {
	ID        string
	SortOrder int32
	Type      string
	Label     string
	Name      pgtype.Text
	Phone     pgtype.Text
	Address   pgtype.Text
	FieldKey  pgtype.Text
}

func (q *Queries) ListEmergencyRows(ctx context.Context) ([]*ListEmergencyRowsRow, error) {
	rows, err := q.db.Query(ctx, listEmergencyRows)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []*ListEmergencyRowsRow
	for rows.Next() {
		var i ListEmergencyRowsRow
		if err := rows.Scan(
			&i.ID,
			&i.SortOrder,
			&i.Type,
			&i.Label,
			&i.Name,
			&i.Phone,
			&i.Address,
			&i.FieldKey,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const reorderEmergencyRows = `-- name: ReorderEmergencyRows :exec
UPDATE emergency_rows AS e
SET sort_order = v.ord - 1
FROM unnest($1::text[]) WITH ORDINALITY AS v(id, ord)
WHERE e.id = v.id AND e.deleted_at IS NULL
`

// Set sort_order to each id's position in the supplied ordered list.
func (q *Queries) ReorderEmergencyRows(ctx context.Context, ids []string) error {
	_, err := q.db.Exec(ctx, reorderEmergencyRows, ids)
	return err
}

const softDeleteEmergencyRow = `-- name: SoftDeleteEmergencyRow :exec
UPDATE emergency_rows SET deleted_at = NOW() WHERE id = $1 AND deleted_at IS NULL
`

func (q *Queries) SoftDeleteEmergencyRow(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, softDeleteEmergencyRow, id)
	return err
}

const upsertEmergencyRow = `-- name: UpsertEmergencyRow :exec

INSERT INTO emergency_rows (id, sort_order, type, label, name, phone, address, field_key, logged_by, test)
VALUES ($1,
        COALESCE((SELECT MAX(sort_order) + 1 FROM emergency_rows WHERE deleted_at IS NULL), 0),
        $2, $3, $4, $5, $6, $7, $8, $9)
ON CONFLICT (id) DO UPDATE
    SET type       = EXCLUDED.type,
        label      = EXCLUDED.label,
        name       = EXCLUDED.name,
        phone      = EXCLUDED.phone,
        address    = EXCLUDED.address,
        field_key  = EXCLUDED.field_key,
        logged_by  = EXCLUDED.logged_by,
        deleted_at = NULL
`

type UpsertEmergencyRowParams struct {
	ID       string
	Type     string
	Label    string
	Name     pgtype.Text
	Phone    pgtype.Text
	Address  pgtype.Text
	FieldKey pgtype.Text
	LoggedBy string
	Test     bool
}

// Emergency card rows (ROADMAP-0011 effort 0011.4). Standing config — eventTest
// only (not pre-birth-forced), so real contacts entered before birth survive the
// clean-slate. ids are dashboard-provided strings (ec- prefixed). Live-field rows
// carry only field_key; their value resolves client-side off existing sensors.
// A new row appends at the end; an edit keeps the row's existing position. The
// explicit order is set by ada.emergency.reorder.
func (q *Queries) UpsertEmergencyRow(ctx context.Context, arg *UpsertEmergencyRowParams) error {
	_, err := q.db.Exec(ctx, upsertEmergencyRow,
		arg.ID,
		arg.Type,
		arg.Label,
		arg.Name,
		arg.Phone,
		arg.Address,
		arg.FieldKey,
		arg.LoggedBy,
		arg.Test,
	)
	return err
}
