// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: feedings.sql

package store

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getLast24hFeedings = `-- name: GetLast24hFeedings :many
SELECT
    f.id,
    f.timestamp,
    f.source,
    COALESCE(d.amount_oz, 0)::float8       AS amount_oz,
    COALESCE(d.breast_milk_oz, 0)::float8  AS breast_milk_oz,
    COALESCE(d.formula_oz, 0)::float8      AS formula_oz,
    COALESCE(
        SUM(CASE WHEN fs.side = 'left'  THEN fs.duration_s END), 0
    )::int AS left_duration_s,
    COALESCE(
        SUM(CASE WHEN fs.side = 'right' THEN fs.duration_s END), 0
    )::int AS right_duration_s
FROM feedings f
LEFT JOIN feeding_bottle_detail d ON d.feeding_id = f.id
LEFT JOIN feeding_segments fs     ON fs.feeding_id = f.id
WHERE f.deleted_at IS NULL
  AND f.timestamp >= NOW() - INTERVAL '24 hours'
GROUP BY
    f.id, f.timestamp, f.source,
    d.amount_oz, d.breast_milk_oz, d.formula_oz
ORDER BY f.timestamp DESC
`

type GetLast24hFeedingsRow struct {
	ID             pgtype.UUID
	Timestamp      pgtype.Timestamptz
	Source         string
	AmountOz       float64
	BreastMilkOz   float64
	FormulaOz      float64
	LeftDurationS  int32
	RightDurationS int32
}

// Returns all feedings in the last 24 hours with per-side breast durations
// and bottle amounts. Left/right duration_s are 0 for non-breast sessions.
// COALESCE handles NULL oz columns from LEFT JOIN on non-bottle feedings.
func (q *Queries) GetLast24hFeedings(ctx context.Context) ([]*GetLast24hFeedingsRow, error) {
	rows, err := q.db.Query(ctx, getLast24hFeedings)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []*GetLast24hFeedingsRow
	for rows.Next() {
		var i GetLast24hFeedingsRow
		if err := rows.Scan(
			&i.ID,
			&i.Timestamp,
			&i.Source,
			&i.AmountOz,
			&i.BreastMilkOz,
			&i.FormulaOz,
			&i.LeftDurationS,
			&i.RightDurationS,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getLastFeeding = `-- name: GetLastFeeding :one
SELECT
    f.timestamp,
    f.source,
    EXISTS(SELECT 1 FROM feeding_bottle_detail d WHERE d.feeding_id = f.id) AS has_bottle_detail
FROM feedings f
WHERE f.deleted_at IS NULL
ORDER BY f.timestamp DESC LIMIT 1
`

type GetLastFeedingRow struct {
	Timestamp       pgtype.Timestamptz
	Source          string
	HasBottleDetail bool
}

func (q *Queries) GetLastFeeding(ctx context.Context) (*GetLastFeedingRow, error) {
	row := q.db.QueryRow(ctx, getLastFeeding)
	var i GetLastFeedingRow
	err := row.Scan(&i.Timestamp, &i.Source, &i.HasBottleDetail)
	return &i, err
}

const getLastFeedingID = `-- name: GetLastFeedingID :one
SELECT id FROM feedings
WHERE deleted_at IS NULL
ORDER BY timestamp DESC LIMIT 1
`

func (q *Queries) GetLastFeedingID(ctx context.Context) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, getLastFeedingID)
	var id pgtype.UUID
	err := row.Scan(&id)
	return id, err
}

const getTodayFeedingAggregates = `-- name: GetTodayFeedingAggregates :one
SELECT
    COUNT(DISTINCT f.id)::int                                        AS count,
    COALESCE(SUM(d.amount_oz), 0)::float8                            AS total_oz,
    COALESCE(SUM(d.breast_milk_oz), 0)::float8                       AS breast_milk_oz,
    COALESCE(SUM(d.formula_oz), 0)::float8                           AS formula_oz
FROM feedings f
LEFT JOIN feeding_bottle_detail d ON d.feeding_id = f.id
WHERE f.deleted_at IS NULL
  AND f.timestamp >= NOW()::date
`

type GetTodayFeedingAggregatesRow struct {
	Count        int32
	TotalOz      float64
	BreastMilkOz float64
	FormulaOz    float64
}

func (q *Queries) GetTodayFeedingAggregates(ctx context.Context) (*GetTodayFeedingAggregatesRow, error) {
	row := q.db.QueryRow(ctx, getTodayFeedingAggregates)
	var i GetTodayFeedingAggregatesRow
	err := row.Scan(
		&i.Count,
		&i.TotalOz,
		&i.BreastMilkOz,
		&i.FormulaOz,
	)
	return &i, err
}

const insertFeeding = `-- name: InsertFeeding :one
INSERT INTO feedings (timestamp, source, logged_by)
VALUES ($1, $2, $3)
RETURNING id
`

type InsertFeedingParams struct {
	Timestamp pgtype.Timestamptz
	Source    string
	LoggedBy  string
}

func (q *Queries) InsertFeeding(ctx context.Context, arg *InsertFeedingParams) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, insertFeeding, arg.Timestamp, arg.Source, arg.LoggedBy)
	var id pgtype.UUID
	err := row.Scan(&id)
	return id, err
}

const insertFeedingBottleDetail = `-- name: InsertFeedingBottleDetail :exec
INSERT INTO feeding_bottle_detail (feeding_id, amount_oz, breast_milk_oz, formula_oz, duration_s)
VALUES ($1, $2, $3, $4, $5)
`

type InsertFeedingBottleDetailParams struct {
	FeedingID    pgtype.UUID
	AmountOz     pgtype.Numeric
	BreastMilkOz pgtype.Numeric
	FormulaOz    pgtype.Numeric
	DurationS    pgtype.Int4
}

func (q *Queries) InsertFeedingBottleDetail(ctx context.Context, arg *InsertFeedingBottleDetailParams) error {
	_, err := q.db.Exec(ctx, insertFeedingBottleDetail,
		arg.FeedingID,
		arg.AmountOz,
		arg.BreastMilkOz,
		arg.FormulaOz,
		arg.DurationS,
	)
	return err
}

const insertFeedingSegment = `-- name: InsertFeedingSegment :exec
INSERT INTO feeding_segments (feeding_id, side, started_at, ended_at, duration_s)
VALUES ($1, $2, $3, $4, $5)
`

type InsertFeedingSegmentParams struct {
	FeedingID pgtype.UUID
	Side      string
	StartedAt pgtype.Timestamptz
	EndedAt   pgtype.Timestamptz
	DurationS int32
}

func (q *Queries) InsertFeedingSegment(ctx context.Context, arg *InsertFeedingSegmentParams) error {
	_, err := q.db.Exec(ctx, insertFeedingSegment,
		arg.FeedingID,
		arg.Side,
		arg.StartedAt,
		arg.EndedAt,
		arg.DurationS,
	)
	return err
}
