// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: growth.sql

package store

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getAllGrowthMeasurements = `-- name: GetAllGrowthMeasurements :many
SELECT id, measured_at, weight_oz, length_in, head_circumference_in,
       source, weight_pct, length_pct, head_pct, logged_by
FROM growth_measurements
WHERE deleted_at IS NULL
ORDER BY measured_at DESC
`

type GetAllGrowthMeasurementsRow struct {
	ID                  pgtype.UUID
	MeasuredAt          pgtype.Timestamptz
	WeightOz            pgtype.Numeric
	LengthIn            pgtype.Numeric
	HeadCircumferenceIn pgtype.Numeric
	Source              string
	WeightPct           pgtype.Numeric
	LengthPct           pgtype.Numeric
	HeadPct             pgtype.Numeric
	LoggedBy            string
}

func (q *Queries) GetAllGrowthMeasurements(ctx context.Context) ([]*GetAllGrowthMeasurementsRow, error) {
	rows, err := q.db.Query(ctx, getAllGrowthMeasurements)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []*GetAllGrowthMeasurementsRow
	for rows.Next() {
		var i GetAllGrowthMeasurementsRow
		if err := rows.Scan(
			&i.ID,
			&i.MeasuredAt,
			&i.WeightOz,
			&i.LengthIn,
			&i.HeadCircumferenceIn,
			&i.Source,
			&i.WeightPct,
			&i.LengthPct,
			&i.HeadPct,
			&i.LoggedBy,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getLatestHeadCircumference = `-- name: GetLatestHeadCircumference :one
SELECT id, measured_at, head_circumference_in, head_pct, source
FROM growth_measurements
WHERE head_circumference_in IS NOT NULL AND deleted_at IS NULL
ORDER BY measured_at DESC
LIMIT 1
`

type GetLatestHeadCircumferenceRow struct {
	ID                  pgtype.UUID
	MeasuredAt          pgtype.Timestamptz
	HeadCircumferenceIn pgtype.Numeric
	HeadPct             pgtype.Numeric
	Source              string
}

func (q *Queries) GetLatestHeadCircumference(ctx context.Context) (*GetLatestHeadCircumferenceRow, error) {
	row := q.db.QueryRow(ctx, getLatestHeadCircumference)
	var i GetLatestHeadCircumferenceRow
	err := row.Scan(
		&i.ID,
		&i.MeasuredAt,
		&i.HeadCircumferenceIn,
		&i.HeadPct,
		&i.Source,
	)
	return &i, err
}

const getLatestLength = `-- name: GetLatestLength :one
SELECT id, measured_at, length_in, length_pct, source
FROM growth_measurements
WHERE length_in IS NOT NULL AND deleted_at IS NULL
ORDER BY measured_at DESC
LIMIT 1
`

type GetLatestLengthRow struct {
	ID         pgtype.UUID
	MeasuredAt pgtype.Timestamptz
	LengthIn   pgtype.Numeric
	LengthPct  pgtype.Numeric
	Source     string
}

func (q *Queries) GetLatestLength(ctx context.Context) (*GetLatestLengthRow, error) {
	row := q.db.QueryRow(ctx, getLatestLength)
	var i GetLatestLengthRow
	err := row.Scan(
		&i.ID,
		&i.MeasuredAt,
		&i.LengthIn,
		&i.LengthPct,
		&i.Source,
	)
	return &i, err
}

const getLatestWeight = `-- name: GetLatestWeight :one
SELECT id, measured_at, weight_oz, weight_pct, source
FROM growth_measurements
WHERE weight_oz IS NOT NULL AND deleted_at IS NULL
ORDER BY measured_at DESC
LIMIT 1
`

type GetLatestWeightRow struct {
	ID         pgtype.UUID
	MeasuredAt pgtype.Timestamptz
	WeightOz   pgtype.Numeric
	WeightPct  pgtype.Numeric
	Source     string
}

func (q *Queries) GetLatestWeight(ctx context.Context) (*GetLatestWeightRow, error) {
	row := q.db.QueryRow(ctx, getLatestWeight)
	var i GetLatestWeightRow
	err := row.Scan(
		&i.ID,
		&i.MeasuredAt,
		&i.WeightOz,
		&i.WeightPct,
		&i.Source,
	)
	return &i, err
}

const insertGrowthMeasurement = `-- name: InsertGrowthMeasurement :one
INSERT INTO growth_measurements (
    measured_at, weight_oz, length_in, head_circumference_in,
    source, weight_pct, length_pct, head_pct, logged_by
) VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
RETURNING id
`

type InsertGrowthMeasurementParams struct {
	MeasuredAt          pgtype.Timestamptz
	WeightOz            pgtype.Numeric
	LengthIn            pgtype.Numeric
	HeadCircumferenceIn pgtype.Numeric
	Source              string
	WeightPct           pgtype.Numeric
	LengthPct           pgtype.Numeric
	HeadPct             pgtype.Numeric
	LoggedBy            string
}

func (q *Queries) InsertGrowthMeasurement(ctx context.Context, arg *InsertGrowthMeasurementParams) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, insertGrowthMeasurement,
		arg.MeasuredAt,
		arg.WeightOz,
		arg.LengthIn,
		arg.HeadCircumferenceIn,
		arg.Source,
		arg.WeightPct,
		arg.LengthPct,
		arg.HeadPct,
		arg.LoggedBy,
	)
	var id pgtype.UUID
	err := row.Scan(&id)
	return id, err
}
