// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: medications.sql

package store

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countGivenForRoutine = `-- name: CountGivenForRoutine :one

SELECT count(*)::int FROM medication_events
WHERE routine_id = $1 AND status = 'given' AND deleted_at IS NULL
`

// ── Server-owned computations (ROADMAP-0011 effort 0011.3) ────────────────────
// Total given doses for a routine (drives max_doses auto-complete; not windowed).
func (q *Queries) CountGivenForRoutine(ctx context.Context, routineID pgtype.Text) (int32, error) {
	row := q.db.QueryRow(ctx, countGivenForRoutine, routineID)
	var column_1 int32
	err := row.Scan(&column_1)
	return column_1, err
}

const endMedicationSeries = `-- name: EndMedicationSeries :exec
UPDATE medication_temp_series
SET status = $1, ended_reason = $2
WHERE id = $3 AND deleted_at IS NULL
`

type EndMedicationSeriesParams struct {
	Status      string
	EndedReason pgtype.Text
	ID          string
}

func (q *Queries) EndMedicationSeries(ctx context.Context, arg *EndMedicationSeriesParams) error {
	_, err := q.db.Exec(ctx, endMedicationSeries, arg.Status, arg.EndedReason, arg.ID)
	return err
}

const getLastGivenForMedication = `-- name: GetLastGivenForMedication :one
SELECT timestamp FROM medication_events
WHERE medication_id = $1 AND status = 'given' AND deleted_at IS NULL
ORDER BY timestamp DESC LIMIT 1
`

func (q *Queries) GetLastGivenForMedication(ctx context.Context, medicationID string) (pgtype.Timestamptz, error) {
	row := q.db.QueryRow(ctx, getLastGivenForMedication, medicationID)
	var timestamp pgtype.Timestamptz
	err := row.Scan(&timestamp)
	return timestamp, err
}

const insertMedicationEvent = `-- name: InsertMedicationEvent :exec

INSERT INTO medication_events (id, medication_id, status, timestamp, routine_id, slot_time,
    dose_amount, dose_unit, source, within_window_override, series_id, started_watch, notes, logged_by, test)
VALUES ($1, $2, $3, $4, $5, $6,
    $7, $8, $9, $10, $11, $12, $13, $14, $15)
ON CONFLICT (id) DO UPDATE
    SET status                 = EXCLUDED.status,
        timestamp              = EXCLUDED.timestamp,
        routine_id             = EXCLUDED.routine_id,
        slot_time              = EXCLUDED.slot_time,
        dose_amount            = EXCLUDED.dose_amount,
        dose_unit              = EXCLUDED.dose_unit,
        source                 = EXCLUDED.source,
        within_window_override = EXCLUDED.within_window_override,
        series_id              = EXCLUDED.series_id,
        started_watch          = EXCLUDED.started_watch,
        notes                  = EXCLUDED.notes,
        logged_by              = EXCLUDED.logged_by,
        deleted_at             = NULL
`

type InsertMedicationEventParams struct {
	ID                   string
	MedicationID         string
	Status               string
	Timestamp            pgtype.Timestamptz
	RoutineID            pgtype.Text
	SlotTime             pgtype.Text
	DoseAmount           pgtype.Numeric
	DoseUnit             pgtype.Text
	Source               pgtype.Text
	WithinWindowOverride bool
	SeriesID             pgtype.Text
	StartedWatch         bool
	Notes                pgtype.Text
	LoggedBy             string
	Test                 bool
}

// ── Dose events + temporary series (ROADMAP-0011 effort 0011.2) ────────────────
func (q *Queries) InsertMedicationEvent(ctx context.Context, arg *InsertMedicationEventParams) error {
	_, err := q.db.Exec(ctx, insertMedicationEvent,
		arg.ID,
		arg.MedicationID,
		arg.Status,
		arg.Timestamp,
		arg.RoutineID,
		arg.SlotTime,
		arg.DoseAmount,
		arg.DoseUnit,
		arg.Source,
		arg.WithinWindowOverride,
		arg.SeriesID,
		arg.StartedWatch,
		arg.Notes,
		arg.LoggedBy,
		arg.Test,
	)
	return err
}

const insertMedicationSeries = `-- name: InsertMedicationSeries :exec
INSERT INTO medication_temp_series (id, medication_id, interval_hours, anchor_dose_id, status, logged_by, test)
VALUES ($1, $2, $3, $4, 'active', $5, $6)
ON CONFLICT (id) DO UPDATE
    SET interval_hours = EXCLUDED.interval_hours,
        anchor_dose_id = EXCLUDED.anchor_dose_id,
        status         = 'active',
        logged_by      = EXCLUDED.logged_by,
        deleted_at     = NULL
`

type InsertMedicationSeriesParams struct {
	ID            string
	MedicationID  string
	IntervalHours pgtype.Numeric
	AnchorDoseID  pgtype.Text
	LoggedBy      string
	Test          bool
}

func (q *Queries) InsertMedicationSeries(ctx context.Context, arg *InsertMedicationSeriesParams) error {
	_, err := q.db.Exec(ctx, insertMedicationSeries,
		arg.ID,
		arg.MedicationID,
		arg.IntervalHours,
		arg.AnchorDoseID,
		arg.LoggedBy,
		arg.Test,
	)
	return err
}

const listActiveMedicationSeries = `-- name: ListActiveMedicationSeries :many
SELECT id, medication_id, interval_hours, anchor_dose_id, status, ended_reason
FROM medication_temp_series
WHERE deleted_at IS NULL AND status = 'active'
ORDER BY created_at
`

type ListActiveMedicationSeriesRow struct {
	ID            string
	MedicationID  string
	IntervalHours pgtype.Numeric
	AnchorDoseID  pgtype.Text
	Status        string
	EndedReason   pgtype.Text
}

func (q *Queries) ListActiveMedicationSeries(ctx context.Context) ([]*ListActiveMedicationSeriesRow, error) {
	rows, err := q.db.Query(ctx, listActiveMedicationSeries)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []*ListActiveMedicationSeriesRow
	for rows.Next() {
		var i ListActiveMedicationSeriesRow
		if err := rows.Scan(
			&i.ID,
			&i.MedicationID,
			&i.IntervalHours,
			&i.AnchorDoseID,
			&i.Status,
			&i.EndedReason,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMedicationRoutines = `-- name: ListMedicationRoutines :many
SELECT id, medication_id, dose_amount, schedule_type, fixed_times, interval_hours, end_type, end_value, status, logged_by, test
FROM medication_routines
WHERE deleted_at IS NULL
ORDER BY created_at
`

type ListMedicationRoutinesRow struct {
	ID            string
	MedicationID  string
	DoseAmount    pgtype.Numeric
	ScheduleType  string
	FixedTimes    []string
	IntervalHours pgtype.Numeric
	EndType       string
	EndValue      pgtype.Text
	Status        string
	LoggedBy      string
	Test          bool
}

func (q *Queries) ListMedicationRoutines(ctx context.Context) ([]*ListMedicationRoutinesRow, error) {
	rows, err := q.db.Query(ctx, listMedicationRoutines)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []*ListMedicationRoutinesRow
	for rows.Next() {
		var i ListMedicationRoutinesRow
		if err := rows.Scan(
			&i.ID,
			&i.MedicationID,
			&i.DoseAmount,
			&i.ScheduleType,
			&i.FixedTimes,
			&i.IntervalHours,
			&i.EndType,
			&i.EndValue,
			&i.Status,
			&i.LoggedBy,
			&i.Test,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMedications = `-- name: ListMedications :many
SELECT id, name, route, measure_unit, min_interval_hours, max_per_24h, active, logged_by, test
FROM medications
WHERE deleted_at IS NULL
ORDER BY name
`

type ListMedicationsRow struct {
	ID               string
	Name             string
	Route            string
	MeasureUnit      string
	MinIntervalHours pgtype.Numeric
	MaxPer24h        pgtype.Int4
	Active           bool
	LoggedBy         string
	Test             bool
}

func (q *Queries) ListMedications(ctx context.Context) ([]*ListMedicationsRow, error) {
	rows, err := q.db.Query(ctx, listMedications)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []*ListMedicationsRow
	for rows.Next() {
		var i ListMedicationsRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Route,
			&i.MeasureUnit,
			&i.MinIntervalHours,
			&i.MaxPer24h,
			&i.Active,
			&i.LoggedBy,
			&i.Test,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRecentMedicationEvents = `-- name: ListRecentMedicationEvents :many
SELECT id, medication_id, status, timestamp, routine_id, slot_time, dose_amount, dose_unit,
    source, within_window_override, series_id, started_watch, notes, logged_by
FROM medication_events
WHERE deleted_at IS NULL AND timestamp >= $1
ORDER BY timestamp DESC
`

type ListRecentMedicationEventsRow struct {
	ID                   string
	MedicationID         string
	Status               string
	Timestamp            pgtype.Timestamptz
	RoutineID            pgtype.Text
	SlotTime             pgtype.Text
	DoseAmount           pgtype.Numeric
	DoseUnit             pgtype.Text
	Source               pgtype.Text
	WithinWindowOverride bool
	SeriesID             pgtype.Text
	StartedWatch         bool
	Notes                pgtype.Text
	LoggedBy             string
}

func (q *Queries) ListRecentMedicationEvents(ctx context.Context, since pgtype.Timestamptz) ([]*ListRecentMedicationEventsRow, error) {
	rows, err := q.db.Query(ctx, listRecentMedicationEvents, since)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []*ListRecentMedicationEventsRow
	for rows.Next() {
		var i ListRecentMedicationEventsRow
		if err := rows.Scan(
			&i.ID,
			&i.MedicationID,
			&i.Status,
			&i.Timestamp,
			&i.RoutineID,
			&i.SlotTime,
			&i.DoseAmount,
			&i.DoseUnit,
			&i.Source,
			&i.WithinWindowOverride,
			&i.SeriesID,
			&i.StartedWatch,
			&i.Notes,
			&i.LoggedBy,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setRoutineStatus = `-- name: SetRoutineStatus :exec
UPDATE medication_routines SET status = $1 WHERE id = $2 AND deleted_at IS NULL
`

type SetRoutineStatusParams struct {
	Status string
	ID     string
}

func (q *Queries) SetRoutineStatus(ctx context.Context, arg *SetRoutineStatusParams) error {
	_, err := q.db.Exec(ctx, setRoutineStatus, arg.Status, arg.ID)
	return err
}

const softDeleteMedication = `-- name: SoftDeleteMedication :exec
UPDATE medications SET deleted_at = NOW() WHERE id = $1 AND deleted_at IS NULL
`

func (q *Queries) SoftDeleteMedication(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, softDeleteMedication, id)
	return err
}

const softDeleteMedicationEvent = `-- name: SoftDeleteMedicationEvent :exec
UPDATE medication_events SET deleted_at = NOW() WHERE id = $1 AND deleted_at IS NULL
`

func (q *Queries) SoftDeleteMedicationEvent(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, softDeleteMedicationEvent, id)
	return err
}

const softDeleteRoutine = `-- name: SoftDeleteRoutine :exec
UPDATE medication_routines SET deleted_at = NOW() WHERE id = $1 AND deleted_at IS NULL
`

func (q *Queries) SoftDeleteRoutine(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, softDeleteRoutine, id)
	return err
}

const softDeleteRoutinesForMedication = `-- name: SoftDeleteRoutinesForMedication :exec
UPDATE medication_routines SET deleted_at = NOW() WHERE medication_id = $1 AND deleted_at IS NULL
`

func (q *Queries) SoftDeleteRoutinesForMedication(ctx context.Context, medicationID string) error {
	_, err := q.db.Exec(ctx, softDeleteRoutinesForMedication, medicationID)
	return err
}

const softDeleteSeriesForMedication = `-- name: SoftDeleteSeriesForMedication :exec
UPDATE medication_temp_series SET deleted_at = NOW() WHERE medication_id = $1 AND deleted_at IS NULL
`

func (q *Queries) SoftDeleteSeriesForMedication(ctx context.Context, medicationID string) error {
	_, err := q.db.Exec(ctx, softDeleteSeriesForMedication, medicationID)
	return err
}

const updateMedicationEvent = `-- name: UpdateMedicationEvent :exec
UPDATE medication_events
SET timestamp = $1, dose_amount = $2
WHERE id = $3 AND deleted_at IS NULL
`

type UpdateMedicationEventParams struct {
	Timestamp  pgtype.Timestamptz
	DoseAmount pgtype.Numeric
	ID         string
}

// History dose correction: timestamp + dose only. The actor (logged_by) is the
// immutable record of who administered the dose and is never rewritten by an edit.
func (q *Queries) UpdateMedicationEvent(ctx context.Context, arg *UpdateMedicationEventParams) error {
	_, err := q.db.Exec(ctx, updateMedicationEvent, arg.Timestamp, arg.DoseAmount, arg.ID)
	return err
}

const upsertMedication = `-- name: UpsertMedication :exec

INSERT INTO medications (id, name, route, measure_unit, min_interval_hours, max_per_24h, active, logged_by, test)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
ON CONFLICT (id) DO UPDATE
    SET name               = EXCLUDED.name,
        route              = EXCLUDED.route,
        measure_unit       = EXCLUDED.measure_unit,
        min_interval_hours = EXCLUDED.min_interval_hours,
        max_per_24h        = EXCLUDED.max_per_24h,
        active             = EXCLUDED.active,
        logged_by          = EXCLUDED.logged_by,
        deleted_at         = NULL
`

type UpsertMedicationParams struct {
	ID               string
	Name             string
	Route            string
	MeasureUnit      string
	MinIntervalHours pgtype.Numeric
	MaxPer24h        pgtype.Int4
	Active           bool
	LoggedBy         string
	Test             bool
}

// Medication registry + dosing routines (ROADMAP-0011 effort 0011.1).
// ids are client-generated (dashboard), so writes are upserts by id; a re-upsert
// revives a soft-deleted row (deleted_at = NULL). The test flag is set on insert
// and left untouched on update, so an edit never reclassifies a real row as test.
func (q *Queries) UpsertMedication(ctx context.Context, arg *UpsertMedicationParams) error {
	_, err := q.db.Exec(ctx, upsertMedication,
		arg.ID,
		arg.Name,
		arg.Route,
		arg.MeasureUnit,
		arg.MinIntervalHours,
		arg.MaxPer24h,
		arg.Active,
		arg.LoggedBy,
		arg.Test,
	)
	return err
}

const upsertMedicationRoutine = `-- name: UpsertMedicationRoutine :exec
INSERT INTO medication_routines (id, medication_id, dose_amount, schedule_type, fixed_times, interval_hours, end_type, end_value, status, logged_by, test)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11)
ON CONFLICT (id) DO UPDATE
    SET medication_id  = EXCLUDED.medication_id,
        dose_amount    = EXCLUDED.dose_amount,
        schedule_type  = EXCLUDED.schedule_type,
        fixed_times    = EXCLUDED.fixed_times,
        interval_hours = EXCLUDED.interval_hours,
        end_type       = EXCLUDED.end_type,
        end_value      = EXCLUDED.end_value,
        status         = EXCLUDED.status,
        logged_by      = EXCLUDED.logged_by,
        deleted_at     = NULL
`

type UpsertMedicationRoutineParams struct {
	ID            string
	MedicationID  string
	DoseAmount    pgtype.Numeric
	ScheduleType  string
	FixedTimes    []string
	IntervalHours pgtype.Numeric
	EndType       string
	EndValue      pgtype.Text
	Status        string
	LoggedBy      string
	Test          bool
}

func (q *Queries) UpsertMedicationRoutine(ctx context.Context, arg *UpsertMedicationRoutineParams) error {
	_, err := q.db.Exec(ctx, upsertMedicationRoutine,
		arg.ID,
		arg.MedicationID,
		arg.DoseAmount,
		arg.ScheduleType,
		arg.FixedTimes,
		arg.IntervalHours,
		arg.EndType,
		arg.EndValue,
		arg.Status,
		arg.LoggedBy,
		arg.Test,
	)
	return err
}
