// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: medications.sql

package store

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const listMedicationRoutines = `-- name: ListMedicationRoutines :many
SELECT id, medication_id, dose_amount, schedule_type, fixed_times, interval_hours, end_type, end_value, status, logged_by, test
FROM medication_routines
WHERE deleted_at IS NULL
ORDER BY created_at
`

type ListMedicationRoutinesRow struct {
	ID            pgtype.UUID
	MedicationID  pgtype.UUID
	DoseAmount    pgtype.Numeric
	ScheduleType  string
	FixedTimes    []string
	IntervalHours pgtype.Numeric
	EndType       string
	EndValue      pgtype.Text
	Status        string
	LoggedBy      string
	Test          bool
}

func (q *Queries) ListMedicationRoutines(ctx context.Context) ([]*ListMedicationRoutinesRow, error) {
	rows, err := q.db.Query(ctx, listMedicationRoutines)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []*ListMedicationRoutinesRow
	for rows.Next() {
		var i ListMedicationRoutinesRow
		if err := rows.Scan(
			&i.ID,
			&i.MedicationID,
			&i.DoseAmount,
			&i.ScheduleType,
			&i.FixedTimes,
			&i.IntervalHours,
			&i.EndType,
			&i.EndValue,
			&i.Status,
			&i.LoggedBy,
			&i.Test,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMedications = `-- name: ListMedications :many
SELECT id, name, route, measure_unit, min_interval_hours, max_per_24h, active, logged_by, test
FROM medications
WHERE deleted_at IS NULL
ORDER BY name
`

type ListMedicationsRow struct {
	ID               pgtype.UUID
	Name             string
	Route            string
	MeasureUnit      string
	MinIntervalHours pgtype.Numeric
	MaxPer24h        pgtype.Int4
	Active           bool
	LoggedBy         string
	Test             bool
}

func (q *Queries) ListMedications(ctx context.Context) ([]*ListMedicationsRow, error) {
	rows, err := q.db.Query(ctx, listMedications)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []*ListMedicationsRow
	for rows.Next() {
		var i ListMedicationsRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Route,
			&i.MeasureUnit,
			&i.MinIntervalHours,
			&i.MaxPer24h,
			&i.Active,
			&i.LoggedBy,
			&i.Test,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const softDeleteMedication = `-- name: SoftDeleteMedication :exec
UPDATE medications SET deleted_at = NOW() WHERE id = $1 AND deleted_at IS NULL
`

func (q *Queries) SoftDeleteMedication(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, softDeleteMedication, id)
	return err
}

const softDeleteRoutine = `-- name: SoftDeleteRoutine :exec
UPDATE medication_routines SET deleted_at = NOW() WHERE id = $1 AND deleted_at IS NULL
`

func (q *Queries) SoftDeleteRoutine(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, softDeleteRoutine, id)
	return err
}

const softDeleteRoutinesForMedication = `-- name: SoftDeleteRoutinesForMedication :exec
UPDATE medication_routines SET deleted_at = NOW() WHERE medication_id = $1 AND deleted_at IS NULL
`

func (q *Queries) SoftDeleteRoutinesForMedication(ctx context.Context, medicationID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, softDeleteRoutinesForMedication, medicationID)
	return err
}

const softDeleteSeriesForMedication = `-- name: SoftDeleteSeriesForMedication :exec
UPDATE medication_temp_series SET deleted_at = NOW() WHERE medication_id = $1 AND deleted_at IS NULL
`

func (q *Queries) SoftDeleteSeriesForMedication(ctx context.Context, medicationID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, softDeleteSeriesForMedication, medicationID)
	return err
}

const upsertMedication = `-- name: UpsertMedication :exec

INSERT INTO medications (id, name, route, measure_unit, min_interval_hours, max_per_24h, active, logged_by, test)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
ON CONFLICT (id) DO UPDATE
    SET name               = EXCLUDED.name,
        route              = EXCLUDED.route,
        measure_unit       = EXCLUDED.measure_unit,
        min_interval_hours = EXCLUDED.min_interval_hours,
        max_per_24h        = EXCLUDED.max_per_24h,
        active             = EXCLUDED.active,
        logged_by          = EXCLUDED.logged_by,
        deleted_at         = NULL
`

type UpsertMedicationParams struct {
	ID               pgtype.UUID
	Name             string
	Route            string
	MeasureUnit      string
	MinIntervalHours pgtype.Numeric
	MaxPer24h        pgtype.Int4
	Active           bool
	LoggedBy         string
	Test             bool
}

// Medication registry + dosing routines (ROADMAP-0011 effort 0011.1).
// ids are client-generated (dashboard), so writes are upserts by id; a re-upsert
// revives a soft-deleted row (deleted_at = NULL). The test flag is set on insert
// and left untouched on update, so an edit never reclassifies a real row as test.
func (q *Queries) UpsertMedication(ctx context.Context, arg *UpsertMedicationParams) error {
	_, err := q.db.Exec(ctx, upsertMedication,
		arg.ID,
		arg.Name,
		arg.Route,
		arg.MeasureUnit,
		arg.MinIntervalHours,
		arg.MaxPer24h,
		arg.Active,
		arg.LoggedBy,
		arg.Test,
	)
	return err
}

const upsertMedicationRoutine = `-- name: UpsertMedicationRoutine :exec
INSERT INTO medication_routines (id, medication_id, dose_amount, schedule_type, fixed_times, interval_hours, end_type, end_value, status, logged_by, test)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11)
ON CONFLICT (id) DO UPDATE
    SET medication_id  = EXCLUDED.medication_id,
        dose_amount    = EXCLUDED.dose_amount,
        schedule_type  = EXCLUDED.schedule_type,
        fixed_times    = EXCLUDED.fixed_times,
        interval_hours = EXCLUDED.interval_hours,
        end_type       = EXCLUDED.end_type,
        end_value      = EXCLUDED.end_value,
        status         = EXCLUDED.status,
        logged_by      = EXCLUDED.logged_by,
        deleted_at     = NULL
`

type UpsertMedicationRoutineParams struct {
	ID            pgtype.UUID
	MedicationID  pgtype.UUID
	DoseAmount    pgtype.Numeric
	ScheduleType  string
	FixedTimes    []string
	IntervalHours pgtype.Numeric
	EndType       string
	EndValue      pgtype.Text
	Status        string
	LoggedBy      string
	Test          bool
}

func (q *Queries) UpsertMedicationRoutine(ctx context.Context, arg *UpsertMedicationRoutineParams) error {
	_, err := q.db.Exec(ctx, upsertMedicationRoutine,
		arg.ID,
		arg.MedicationID,
		arg.DoseAmount,
		arg.ScheduleType,
		arg.FixedTimes,
		arg.IntervalHours,
		arg.EndType,
		arg.EndValue,
		arg.Status,
		arg.LoggedBy,
		arg.Test,
	)
	return err
}
