// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package store

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type AdaConfig struct {
	Key       string
	Value     string
	UpdatedAt pgtype.Timestamptz
}

type AdaProfile struct {
	ID        pgtype.UUID
	BirthAt   pgtype.Timestamptz
	Singleton bool
	CreatedAt pgtype.Timestamptz
}

type Diaper struct {
	ID        pgtype.UUID
	Timestamp pgtype.Timestamptz
	Type      string
	LoggedBy  string
	DeletedAt pgtype.Timestamptz
	CreatedAt pgtype.Timestamptz
}

type Feeding struct {
	ID        pgtype.UUID
	Timestamp pgtype.Timestamptz
	Source    string
	LoggedBy  string
	DeletedAt pgtype.Timestamptz
	CreatedAt pgtype.Timestamptz
}

type FeedingBottleDetail struct {
	FeedingID    pgtype.UUID
	AmountOz     pgtype.Numeric
	BreastMilkOz pgtype.Numeric
	FormulaOz    pgtype.Numeric
	DurationS    pgtype.Int4
}

type FeedingSegment struct {
	ID        pgtype.UUID
	FeedingID pgtype.UUID
	Side      string
	StartedAt pgtype.Timestamptz
	EndedAt   pgtype.Timestamptz
	DurationS int32
}

type GrowthMeasurement struct {
	ID                  pgtype.UUID
	MeasuredAt          pgtype.Timestamptz
	WeightOz            pgtype.Numeric
	LengthIn            pgtype.Numeric
	HeadCircumferenceIn pgtype.Numeric
	Source              string
	WeightPct           pgtype.Numeric
	LengthPct           pgtype.Numeric
	HeadPct             pgtype.Numeric
	LoggedBy            string
	DeletedAt           pgtype.Timestamptz
	CreatedAt           pgtype.Timestamptz
}

type Person struct {
	ID          pgtype.UUID
	HaUserID    string
	DisplayName string
	Username    string
	IsCaretaker bool
	DeletedAt   pgtype.Timestamptz
	CreatedAt   pgtype.Timestamptz
	UpdatedAt   pgtype.Timestamptz
}

type PersonChannel struct {
	ID        pgtype.UUID
	PersonID  pgtype.UUID
	Type      string
	Address   string
	Label     pgtype.Text
	IsActive  bool
	CreatedAt pgtype.Timestamptz
}

type SleepSession struct {
	ID        pgtype.UUID
	StartTime pgtype.Timestamptz
	EndTime   pgtype.Timestamptz
	SleepType string
	LoggedBy  string
	DeletedAt pgtype.Timestamptz
	CreatedAt pgtype.Timestamptz
}

type TummyTimeSession struct {
	ID        pgtype.UUID
	StartTime pgtype.Timestamptz
	EndTime   pgtype.Timestamptz
	DurationS int32
	LoggedBy  string
	DeletedAt pgtype.Timestamptz
	CreatedAt pgtype.Timestamptz
}
