// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package store

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type AdaConfig struct {
	Key       string
	Value     string
	UpdatedAt pgtype.Timestamptz
}

type Diaper struct {
	ID        pgtype.UUID
	Timestamp pgtype.Timestamptz
	Type      string
	LoggedBy  string
	DeletedAt pgtype.Timestamptz
	CreatedAt pgtype.Timestamptz
}

type Feeding struct {
	ID        pgtype.UUID
	Timestamp pgtype.Timestamptz
	Source    string
	LoggedBy  string
	DeletedAt pgtype.Timestamptz
	CreatedAt pgtype.Timestamptz
}

type FeedingBottleDetail struct {
	FeedingID    pgtype.UUID
	AmountOz     pgtype.Numeric
	BreastMilkOz pgtype.Numeric
	FormulaOz    pgtype.Numeric
	DurationS    pgtype.Int4
}

type FeedingSegment struct {
	ID        pgtype.UUID
	FeedingID pgtype.UUID
	Side      string
	StartedAt pgtype.Timestamptz
	EndedAt   pgtype.Timestamptz
	DurationS int32
}

type SleepSession struct {
	ID        pgtype.UUID
	StartTime pgtype.Timestamptz
	EndTime   pgtype.Timestamptz
	SleepType string
	LoggedBy  string
	DeletedAt pgtype.Timestamptz
	CreatedAt pgtype.Timestamptz
}

type TummyTimeSession struct {
	ID        pgtype.UUID
	StartTime pgtype.Timestamptz
	EndTime   pgtype.Timestamptz
	DurationS int32
	LoggedBy  string
	DeletedAt pgtype.Timestamptz
	CreatedAt pgtype.Timestamptz
}
