// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package store

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type AdaConfig struct {
	Key       string
	Value     string
	UpdatedAt pgtype.Timestamptz
}

type AdaProfile struct {
	ID        pgtype.UUID
	BirthAt   pgtype.Timestamptz
	Singleton bool
	CreatedAt pgtype.Timestamptz
}

type Diaper struct {
	ID        pgtype.UUID
	Timestamp pgtype.Timestamptz
	Type      string
	LoggedBy  string
	DeletedAt pgtype.Timestamptz
	CreatedAt pgtype.Timestamptz
	Test      bool
}

type EmergencyRow struct {
	ID        string
	SortOrder int32
	Type      string
	Label     string
	Name      pgtype.Text
	Phone     pgtype.Text
	Address   pgtype.Text
	FieldKey  pgtype.Text
	LoggedBy  string
	DeletedAt pgtype.Timestamptz
	CreatedAt pgtype.Timestamptz
	Test      bool
}

type Feeding struct {
	ID        pgtype.UUID
	Timestamp pgtype.Timestamptz
	Source    string
	LoggedBy  string
	DeletedAt pgtype.Timestamptz
	CreatedAt pgtype.Timestamptz
	Test      bool
}

type FeedingBottleDetail struct {
	FeedingID    pgtype.UUID
	AmountOz     pgtype.Numeric
	BreastMilkOz pgtype.Numeric
	FormulaOz    pgtype.Numeric
	DurationS    pgtype.Int4
}

type FeedingSegment struct {
	ID        pgtype.UUID
	FeedingID pgtype.UUID
	Side      string
	StartedAt pgtype.Timestamptz
	EndedAt   pgtype.Timestamptz
	DurationS int32
}

type GrowthMeasurement struct {
	ID                  pgtype.UUID
	MeasuredAt          pgtype.Timestamptz
	WeightOz            pgtype.Numeric
	LengthIn            pgtype.Numeric
	HeadCircumferenceIn pgtype.Numeric
	Source              string
	WeightPct           pgtype.Numeric
	LengthPct           pgtype.Numeric
	HeadPct             pgtype.Numeric
	LoggedBy            string
	DeletedAt           pgtype.Timestamptz
	CreatedAt           pgtype.Timestamptz
	Test                bool
}

type Medication struct {
	ID               string
	Name             string
	Route            string
	MeasureUnit      string
	MinIntervalHours pgtype.Numeric
	MaxPer24h        pgtype.Int4
	Active           bool
	LoggedBy         string
	DeletedAt        pgtype.Timestamptz
	CreatedAt        pgtype.Timestamptz
	Test             bool
}

type MedicationEvent struct {
	ID                   string
	MedicationID         string
	Status               string
	Timestamp            pgtype.Timestamptz
	RoutineID            pgtype.Text
	SlotTime             pgtype.Text
	DoseAmount           pgtype.Numeric
	DoseUnit             pgtype.Text
	Source               pgtype.Text
	WithinWindowOverride bool
	SeriesID             pgtype.Text
	StartedWatch         bool
	Notes                pgtype.Text
	LoggedBy             string
	DeletedAt            pgtype.Timestamptz
	CreatedAt            pgtype.Timestamptz
	Test                 bool
}

type MedicationRoutine struct {
	ID            string
	MedicationID  string
	DoseAmount    pgtype.Numeric
	ScheduleType  string
	FixedTimes    []string
	IntervalHours pgtype.Numeric
	EndType       string
	EndValue      pgtype.Text
	Status        string
	LoggedBy      string
	DeletedAt     pgtype.Timestamptz
	CreatedAt     pgtype.Timestamptz
	Test          bool
}

type MedicationTempSeries struct {
	ID            string
	MedicationID  string
	IntervalHours pgtype.Numeric
	AnchorDoseID  pgtype.Text
	Status        string
	EndedReason   pgtype.Text
	LoggedBy      string
	DeletedAt     pgtype.Timestamptz
	CreatedAt     pgtype.Timestamptz
	Test          bool
}

type Person struct {
	ID          pgtype.UUID
	HaUserID    string
	DisplayName string
	Username    string
	IsCaretaker bool
	DeletedAt   pgtype.Timestamptz
	CreatedAt   pgtype.Timestamptz
	UpdatedAt   pgtype.Timestamptz
}

type PersonChannel struct {
	ID        pgtype.UUID
	PersonID  pgtype.UUID
	Type      string
	Address   string
	Label     pgtype.Text
	IsActive  bool
	CreatedAt pgtype.Timestamptz
}

type SleepSession struct {
	ID        pgtype.UUID
	StartTime pgtype.Timestamptz
	EndTime   pgtype.Timestamptz
	SleepType string
	LoggedBy  string
	DeletedAt pgtype.Timestamptz
	CreatedAt pgtype.Timestamptz
	Test      bool
}

type TummyTimeSession struct {
	ID        pgtype.UUID
	StartTime pgtype.Timestamptz
	EndTime   pgtype.Timestamptz
	DurationS int32
	LoggedBy  string
	DeletedAt pgtype.Timestamptz
	CreatedAt pgtype.Timestamptz
	Test      bool
}
