// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: people.sql

package store

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const addPersonChannel = `-- name: AddPersonChannel :exec
INSERT INTO person_channels (id, person_id, type, address, label)
VALUES (gen_random_uuid(), $1, $2, $3, $4)
ON CONFLICT (person_id, address) DO UPDATE
    SET label     = EXCLUDED.label,
        is_active = true
`

type AddPersonChannelParams struct {
	PersonID pgtype.UUID
	Type     string
	Address  string
	Label    pgtype.Text
}

func (q *Queries) AddPersonChannel(ctx context.Context, arg *AddPersonChannelParams) error {
	_, err := q.db.Exec(ctx, addPersonChannel,
		arg.PersonID,
		arg.Type,
		arg.Address,
		arg.Label,
	)
	return err
}

const getActivePeopleWithChannels = `-- name: GetActivePeopleWithChannels :many
SELECT
    p.id,
    p.display_name,
    pc.type,
    pc.address,
    pc.label
FROM people p
JOIN person_channels pc ON pc.person_id = p.id
WHERE p.deleted_at IS NULL
  AND p.is_caretaker = true
  AND pc.is_active = true
ORDER BY p.display_name, pc.type
`

type GetActivePeopleWithChannelsRow struct {
	ID          pgtype.UUID
	DisplayName string
	Type        string
	Address     string
	Label       pgtype.Text
}

func (q *Queries) GetActivePeopleWithChannels(ctx context.Context) ([]*GetActivePeopleWithChannelsRow, error) {
	rows, err := q.db.Query(ctx, getActivePeopleWithChannels)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []*GetActivePeopleWithChannelsRow
	for rows.Next() {
		var i GetActivePeopleWithChannelsRow
		if err := rows.Scan(
			&i.ID,
			&i.DisplayName,
			&i.Type,
			&i.Address,
			&i.Label,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getAllPeople = `-- name: GetAllPeople :many
SELECT id, ha_user_id, display_name, username, is_caretaker
FROM people
WHERE deleted_at IS NULL
ORDER BY display_name
`

type GetAllPeopleRow struct {
	ID          pgtype.UUID
	HaUserID    string
	DisplayName string
	Username    string
	IsCaretaker bool
}

func (q *Queries) GetAllPeople(ctx context.Context) ([]*GetAllPeopleRow, error) {
	rows, err := q.db.Query(ctx, getAllPeople)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []*GetAllPeopleRow
	for rows.Next() {
		var i GetAllPeopleRow
		if err := rows.Scan(
			&i.ID,
			&i.HaUserID,
			&i.DisplayName,
			&i.Username,
			&i.IsCaretaker,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getChannelsForPerson = `-- name: GetChannelsForPerson :many
SELECT id, type, address, label, is_active
FROM person_channels
WHERE person_id = $1
ORDER BY type, created_at
`

type GetChannelsForPersonRow struct {
	ID       pgtype.UUID
	Type     string
	Address  string
	Label    pgtype.Text
	IsActive bool
}

func (q *Queries) GetChannelsForPerson(ctx context.Context, personID pgtype.UUID) ([]*GetChannelsForPersonRow, error) {
	rows, err := q.db.Query(ctx, getChannelsForPerson, personID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []*GetChannelsForPersonRow
	for rows.Next() {
		var i GetChannelsForPersonRow
		if err := rows.Scan(
			&i.ID,
			&i.Type,
			&i.Address,
			&i.Label,
			&i.IsActive,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getLinkedHAPushAddresses = `-- name: GetLinkedHAPushAddresses :many
SELECT address FROM person_channels
WHERE type = 'ha_push'
`

func (q *Queries) GetLinkedHAPushAddresses(ctx context.Context) ([]string, error) {
	rows, err := q.db.Query(ctx, getLinkedHAPushAddresses)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var address string
		if err := rows.Scan(&address); err != nil {
			return nil, err
		}
		items = append(items, address)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getPersonByHAUserID = `-- name: GetPersonByHAUserID :one
SELECT id, ha_user_id, display_name, username, is_caretaker
FROM people
WHERE ha_user_id = $1
  AND deleted_at IS NULL
`

type GetPersonByHAUserIDRow struct {
	ID          pgtype.UUID
	HaUserID    string
	DisplayName string
	Username    string
	IsCaretaker bool
}

func (q *Queries) GetPersonByHAUserID(ctx context.Context, haUserID string) (*GetPersonByHAUserIDRow, error) {
	row := q.db.QueryRow(ctx, getPersonByHAUserID, haUserID)
	var i GetPersonByHAUserIDRow
	err := row.Scan(
		&i.ID,
		&i.HaUserID,
		&i.DisplayName,
		&i.Username,
		&i.IsCaretaker,
	)
	return &i, err
}

const getPersonHAUserIDs = `-- name: GetPersonHAUserIDs :many
SELECT ha_user_id FROM people
WHERE deleted_at IS NULL
`

func (q *Queries) GetPersonHAUserIDs(ctx context.Context) ([]string, error) {
	rows, err := q.db.Query(ctx, getPersonHAUserIDs)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var ha_user_id string
		if err := rows.Scan(&ha_user_id); err != nil {
			return nil, err
		}
		items = append(items, ha_user_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const removePersonChannel = `-- name: RemovePersonChannel :exec
DELETE FROM person_channels
WHERE id = $1
  AND person_id = $2
`

type RemovePersonChannelParams struct {
	ID       pgtype.UUID
	PersonID pgtype.UUID
}

func (q *Queries) RemovePersonChannel(ctx context.Context, arg *RemovePersonChannelParams) error {
	_, err := q.db.Exec(ctx, removePersonChannel, arg.ID, arg.PersonID)
	return err
}

const softDeletePerson = `-- name: SoftDeletePerson :exec
UPDATE people
SET deleted_at = NOW(), updated_at = NOW()
WHERE ha_user_id = $1
  AND deleted_at IS NULL
`

func (q *Queries) SoftDeletePerson(ctx context.Context, haUserID string) error {
	_, err := q.db.Exec(ctx, softDeletePerson, haUserID)
	return err
}

const updateCaretakerStatus = `-- name: UpdateCaretakerStatus :exec
UPDATE people
SET is_caretaker = $1, updated_at = NOW()
WHERE ha_user_id = $2
  AND deleted_at IS NULL
`

type UpdateCaretakerStatusParams struct {
	IsCaretaker bool
	HaUserID    string
}

func (q *Queries) UpdateCaretakerStatus(ctx context.Context, arg *UpdateCaretakerStatusParams) error {
	_, err := q.db.Exec(ctx, updateCaretakerStatus, arg.IsCaretaker, arg.HaUserID)
	return err
}

const upsertPerson = `-- name: UpsertPerson :exec
INSERT INTO people (id, ha_user_id, display_name, username, updated_at)
VALUES (gen_random_uuid(), $1, $2, $3, NOW())
ON CONFLICT (ha_user_id) DO UPDATE
    SET display_name = EXCLUDED.display_name,
        username     = EXCLUDED.username,
        deleted_at   = NULL,
        updated_at   = NOW()
`

type UpsertPersonParams struct {
	HaUserID    string
	DisplayName string
	Username    string
}

func (q *Queries) UpsertPerson(ctx context.Context, arg *UpsertPersonParams) error {
	_, err := q.db.Exec(ctx, upsertPerson, arg.HaUserID, arg.DisplayName, arg.Username)
	return err
}
