// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: profile.sql

package store

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getProfile = `-- name: GetProfile :one
SELECT id, birth_at, created_at FROM ada_profile
LIMIT 1
`

type GetProfileRow struct {
	ID        pgtype.UUID
	BirthAt   pgtype.Timestamptz
	CreatedAt pgtype.Timestamptz
}

func (q *Queries) GetProfile(ctx context.Context) (*GetProfileRow, error) {
	row := q.db.QueryRow(ctx, getProfile)
	var i GetProfileRow
	err := row.Scan(&i.ID, &i.BirthAt, &i.CreatedAt)
	return &i, err
}

const upsertProfile = `-- name: UpsertProfile :exec
INSERT INTO ada_profile (id, birth_at, singleton)
VALUES (gen_random_uuid(), $1, true)
ON CONFLICT (singleton) DO NOTHING
`

// Inserts the birth profile. ON CONFLICT (singleton) DO NOTHING makes this
// idempotent — if ada.born fires more than once, the first write wins and
// subsequent calls are silently ignored. birth_at is immutable once set.
func (q *Queries) UpsertProfile(ctx context.Context, birthAt pgtype.Timestamptz) error {
	_, err := q.db.Exec(ctx, upsertProfile, birthAt)
	return err
}
