// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: sleep.sql

package store

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getActiveSleepSession = `-- name: GetActiveSleepSession :one
SELECT start_time FROM sleep_sessions
WHERE end_time IS NULL AND deleted_at IS NULL
ORDER BY start_time DESC LIMIT 1
`

func (q *Queries) GetActiveSleepSession(ctx context.Context) (pgtype.Timestamptz, error) {
	row := q.db.QueryRow(ctx, getActiveSleepSession)
	var start_time pgtype.Timestamptz
	err := row.Scan(&start_time)
	return start_time, err
}

const getLastSleepEnd = `-- name: GetLastSleepEnd :one
SELECT end_time FROM sleep_sessions
WHERE end_time IS NOT NULL AND deleted_at IS NULL
ORDER BY end_time DESC LIMIT 1
`

func (q *Queries) GetLastSleepEnd(ctx context.Context) (pgtype.Timestamptz, error) {
	row := q.db.QueryRow(ctx, getLastSleepEnd)
	var end_time pgtype.Timestamptz
	err := row.Scan(&end_time)
	return end_time, err
}

const getTodaySleepAggregates = `-- name: GetTodaySleepAggregates :one
SELECT
    COALESCE(EXTRACT(EPOCH FROM SUM(
        LEAST(COALESCE(end_time, NOW()), NOW()) - GREATEST(start_time, $1)
    )) / 3600, 0)::float8 AS total_hours,
    COUNT(*) FILTER (WHERE sleep_type = 'night')::int AS night_count,
    COUNT(*) FILTER (WHERE sleep_type = 'nap')::int   AS nap_count
FROM sleep_sessions
WHERE deleted_at IS NULL
  AND (end_time IS NULL OR end_time > $1)
`

type GetTodaySleepAggregatesRow struct {
	TotalHours float64
	NightCount int32
	NapCount   int32
}

func (q *Queries) GetTodaySleepAggregates(ctx context.Context, boundary pgtype.Timestamptz) (*GetTodaySleepAggregatesRow, error) {
	row := q.db.QueryRow(ctx, getTodaySleepAggregates, boundary)
	var i GetTodaySleepAggregatesRow
	err := row.Scan(&i.TotalHours, &i.NightCount, &i.NapCount)
	return &i, err
}

const getTodaySleepSessions = `-- name: GetTodaySleepSessions :many
SELECT
    id,
    start_time,
    COALESCE(end_time, NOW()) AS end_time,
    sleep_type,
    logged_by,
    (end_time IS NOT NULL)::bool AS is_complete
FROM sleep_sessions
WHERE deleted_at IS NULL
  AND (end_time IS NULL OR end_time > $1)
ORDER BY start_time DESC
`

type GetTodaySleepSessionsRow struct {
	ID         pgtype.UUID
	StartTime  pgtype.Timestamptz
	EndTime    pgtype.Timestamptz
	SleepType  string
	LoggedBy   string
	IsComplete bool
}

// Returns sleep sessions active since the bedtime boundary, newest-first.
// COALESCE ensures end_time is always non-null; is_complete distinguishes
// active sessions (end_time IS NULL) from completed ones.
func (q *Queries) GetTodaySleepSessions(ctx context.Context, boundary pgtype.Timestamptz) ([]*GetTodaySleepSessionsRow, error) {
	rows, err := q.db.Query(ctx, getTodaySleepSessions, boundary)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []*GetTodaySleepSessionsRow
	for rows.Next() {
		var i GetTodaySleepSessionsRow
		if err := rows.Scan(
			&i.ID,
			&i.StartTime,
			&i.EndTime,
			&i.SleepType,
			&i.LoggedBy,
			&i.IsComplete,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const insertSleepSession = `-- name: InsertSleepSession :exec
INSERT INTO sleep_sessions (start_time, end_time, sleep_type, logged_by)
VALUES ($1, $2, $3, $4)
`

type InsertSleepSessionParams struct {
	StartTime pgtype.Timestamptz
	EndTime   pgtype.Timestamptz
	SleepType string
	LoggedBy  string
}

func (q *Queries) InsertSleepSession(ctx context.Context, arg *InsertSleepSessionParams) error {
	_, err := q.db.Exec(ctx, insertSleepSession,
		arg.StartTime,
		arg.EndTime,
		arg.SleepType,
		arg.LoggedBy,
	)
	return err
}

const insertSleepStart = `-- name: InsertSleepStart :one
INSERT INTO sleep_sessions (start_time, sleep_type, logged_by)
VALUES ($1, $2, $3)
RETURNING id
`

type InsertSleepStartParams struct {
	StartTime pgtype.Timestamptz
	SleepType string
	LoggedBy  string
}

func (q *Queries) InsertSleepStart(ctx context.Context, arg *InsertSleepStartParams) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, insertSleepStart, arg.StartTime, arg.SleepType, arg.LoggedBy)
	var id pgtype.UUID
	err := row.Scan(&id)
	return id, err
}

const updateSleepEnd = `-- name: UpdateSleepEnd :exec
UPDATE sleep_sessions
SET end_time = $1
WHERE id = (
    SELECT id FROM sleep_sessions
    WHERE end_time IS NULL AND deleted_at IS NULL
    ORDER BY start_time DESC LIMIT 1
)
`

func (q *Queries) UpdateSleepEnd(ctx context.Context, endTime pgtype.Timestamptz) error {
	_, err := q.db.Exec(ctx, updateSleepEnd, endTime)
	return err
}
