// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: tummy.sql

package store

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getTodayTummyAggregates = `-- name: GetTodayTummyAggregates :one
SELECT
    COALESCE(SUM(duration_s) / 60, 0)::int AS total_minutes,
    COUNT(*)::int                           AS sessions
FROM tummy_time_sessions
WHERE deleted_at IS NULL
  AND start_time >= $1
`

type GetTodayTummyAggregatesRow struct {
	TotalMinutes int32
	Sessions     int32
}

func (q *Queries) GetTodayTummyAggregates(ctx context.Context, boundary pgtype.Timestamptz) (*GetTodayTummyAggregatesRow, error) {
	row := q.db.QueryRow(ctx, getTodayTummyAggregates, boundary)
	var i GetTodayTummyAggregatesRow
	err := row.Scan(&i.TotalMinutes, &i.Sessions)
	return &i, err
}

const insertTummySession = `-- name: InsertTummySession :exec
INSERT INTO tummy_time_sessions (start_time, end_time, duration_s, logged_by)
VALUES ($1, $2, $3, $4)
`

type InsertTummySessionParams struct {
	StartTime pgtype.Timestamptz
	EndTime   pgtype.Timestamptz
	DurationS int32
	LoggedBy  string
}

func (q *Queries) InsertTummySession(ctx context.Context, arg *InsertTummySessionParams) error {
	_, err := q.db.Exec(ctx, insertTummySession,
		arg.StartTime,
		arg.EndTime,
		arg.DurationS,
		arg.LoggedBy,
	)
	return err
}
