// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: tummy.sql

package store

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getLast24hTummy = `-- name: GetLast24hTummy :many
SELECT id, start_time, end_time, duration_s, logged_by
FROM tummy_time_sessions
WHERE deleted_at IS NULL
  AND start_time >= $1
ORDER BY start_time DESC
`

type GetLast24hTummyRow struct {
	ID        pgtype.UUID
	StartTime pgtype.Timestamptz
	EndTime   pgtype.Timestamptz
	DurationS int32
	LoggedBy  string
}

// Returns tummy time sessions since @since (a rolling-24h boundary), newest-first,
// matching the shape of the other *_history sensors.
func (q *Queries) GetLast24hTummy(ctx context.Context, since pgtype.Timestamptz) ([]*GetLast24hTummyRow, error) {
	rows, err := q.db.Query(ctx, getLast24hTummy, since)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []*GetLast24hTummyRow
	for rows.Next() {
		var i GetLast24hTummyRow
		if err := rows.Scan(
			&i.ID,
			&i.StartTime,
			&i.EndTime,
			&i.DurationS,
			&i.LoggedBy,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getTodayTummyAggregates = `-- name: GetTodayTummyAggregates :one
SELECT
    COALESCE(SUM(duration_s) / 60, 0)::int AS total_minutes,
    COUNT(*)::int                           AS sessions
FROM tummy_time_sessions
WHERE deleted_at IS NULL
  AND start_time >= $1
`

type GetTodayTummyAggregatesRow struct {
	TotalMinutes int32
	Sessions     int32
}

func (q *Queries) GetTodayTummyAggregates(ctx context.Context, boundary pgtype.Timestamptz) (*GetTodayTummyAggregatesRow, error) {
	row := q.db.QueryRow(ctx, getTodayTummyAggregates, boundary)
	var i GetTodayTummyAggregatesRow
	err := row.Scan(&i.TotalMinutes, &i.Sessions)
	return &i, err
}

const insertTummySession = `-- name: InsertTummySession :exec
INSERT INTO tummy_time_sessions (start_time, end_time, duration_s, logged_by)
VALUES ($1, $2, $3, $4)
`

type InsertTummySessionParams struct {
	StartTime pgtype.Timestamptz
	EndTime   pgtype.Timestamptz
	DurationS int32
	LoggedBy  string
}

func (q *Queries) InsertTummySession(ctx context.Context, arg *InsertTummySessionParams) error {
	_, err := q.db.Exec(ctx, insertTummySession,
		arg.StartTime,
		arg.EndTime,
		arg.DurationS,
		arg.LoggedBy,
	)
	return err
}

const softDeleteTummySession = `-- name: SoftDeleteTummySession :exec
UPDATE tummy_time_sessions SET deleted_at = NOW() WHERE id = $1 AND deleted_at IS NULL
`

func (q *Queries) SoftDeleteTummySession(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, softDeleteTummySession, id)
	return err
}

const updateTummySession = `-- name: UpdateTummySession :exec
UPDATE tummy_time_sessions
SET start_time = $1, end_time = $2, duration_s = $3, logged_by = $4
WHERE id = $5 AND deleted_at IS NULL
`

type UpdateTummySessionParams struct {
	StartTime pgtype.Timestamptz
	EndTime   pgtype.Timestamptz
	DurationS int32
	LoggedBy  string
	ID        pgtype.UUID
}

func (q *Queries) UpdateTummySession(ctx context.Context, arg *UpdateTummySessionParams) error {
	_, err := q.db.Exec(ctx, updateTummySession,
		arg.StartTime,
		arg.EndTime,
		arg.DurationS,
		arg.LoggedBy,
		arg.ID,
	)
	return err
}
